### ISSUE TITLE
OPAL-1711: Add mechanism to change language from English to French

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#1730]
Jira issue originally created by user @kazoompa:

Currently there are no way of changing the language in Opal.

Add a link at the login page to choose desire language.

Should the user change the language on the fly (not at login)? If so, then the link should be added to the top menu.

**Comment by kazoompa** [comment]
Could be done as in the case of Mica, i.e., under the top menu where user can logout. Before doing so, Opal messages must be properly translated to FR, it's been a while the catalog files were not cleaned up.
