### ISSUE TITLE
OPAL-1787: Add in Administration section a message informing that a new version of Opal is available

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#1754]
Jira issue originally created by user @ymarcon:

**Comment by kazoompa** [comment]
Very useful indeed!

**Comment by ymarcon** [comment]
The opal related news from obiba.org are displayed in the dashboard (since 2.15), with a link to the news details. Then any user can see the advantage of upgrading (not only the admins, that are probably not using the application).
