### ISSUE TITLE
OPAL-2308: Copy task: check that a task with same config is not already running

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#1880]
Jira issue originally created by user @cthiebault:

It will crash if 2 tasks try to copy the same table to the same destination table.

**Comment by kazoompa** [comment]
Difficult to reproduce. Ran a script copy the same table to the same destination table without an error.

```
opal rest /project/ULSAM/commands/_copy -u administrator -p password -ct application/json -m POST < table.json &
opal rest /project/ULSAM/commands/_copy -u administrator -p password -ct application/json -m POST < table.json &
```
Running in background is almost as if they ran simultaneously.

**Comment by ymarcon** [comment]
There is a queue for executing the tasks one after the other. So there is no conflict possible.

**Comment by ymarcon** [comment]
Same task config does not mean that the data are the same. I think it is a task manager that would help, like see task details, reorder execution of the tasks, persist task history, recover task after system restart etc.
