### ISSUE TITLE
OPAL-2346: Allow defining a library of js functions at View level

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#1891]
Jira issue originally created by user @ymarcon:

To make js code reusable in derived variables.

It is already possible to do it at system level, but this feature is hidden...

**Comment by kazoompa** [comment]
More and more the serious stuff is being done at R level. Do we really need this functionality?

**Comment by ymarcon** [comment]
The [source](http://opaldoc.obiba.org/en/latest/magma-user-guide/global/source.html) function is enough for now.
