### ISSUE TITLE
OPAL-2476: Files: It would be nice to be able to use the back button to navigate one folder up when drilling down on folders...

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#1914]
Jira issue originally created by user @emorency:

**Comment by kazoompa** [comment]
As suggested by Sofiya, may be should have a higher level IMPROVEMENT for *Accessibility*.

**Comment by ymarcon** [comment]
I guess it is just a matter of updating/handling the browser history with the path to the file.
