### ISSUE TITLE
OPAL-3024: List of usernames or autocomplete available when assigning permissions to reduce typos

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#2171]
Jira issue originally created by user @tombisho:

When setting permissions, the user has to type in the username that they want to assign the permission to.

Very frequently, there are typos. This leads to a series of emails asking if the permission is set. After several emails, eventually the user sees that they have entered the username incorrectly and corrects this.

It would be better if they were presented with a list of Opal usernames and usernames pulled from agate to choose from, or have some autocomplete

**Comment by hjvdwijk** [comment]
And how about LDAP? Could Opal query an LDAP server for the list of users, to suggest and/or validate usernames?

**Comment by ymarcon** [comment]
Opal uses alternate user repositories for authentication only (OAuth2 protocol): users cannot be queried. Nevertheless, what could be done to facilitate the administration task is the user name completion based on the known users (the ones that are defined in the Opal's user registry, the ones that already logged in and the ones that were already granted a permission) and the group name completion based on the known groups (groups defined in the user registry and groups that are already granted a permission).
