### ISSUE TITLE
Datasource service import usage

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3260]
See technical specification [Datasource Plugins](https://github.com/obiba/opal/wiki/Datasource-Plugins)

The purpose of this task is to make use of the datasource services for enhancing the user interface with self-described form when user is importing data.

* make a JSON schema form renderer in GWT
* use the REST services and DTOs to create a transient datasource and submit an importation task

**Comment by ymarcon** [comment]
Is this possible to specify in the json schema some help texts? 
* free html or markdown text, 
* help text associated to an input widget

**Comment by meek0** [comment]
Help text can be added via the "description" schema property. Right now it "supports" html elements.

**Comment by ymarcon** [comment]
The UI renders the fields in a random order. Field order specified in the import.json file should be maintained.
