### ISSUE TITLE
REDCap datasource plugin to import (meta)data 

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3261]
Implement a [REDCap](https://www.project-redcap.org/) datasource, wrapped in a [Opal datasource service plugin](https://github.com/obiba/opal/wiki/Datasource-Plugins) to get both data and data dictionaries from a REDCap server.

Datasource parameters are:
* REDCap server URI
* REDCap user access token

The plugin will allow to specify these parameters statically (plugin properties configuration), in which case the datasource plugin JSON schema form will not request these parameters from user at importation time. 

Useful links:
* [REDCap Tools](http://redcap-tools.github.io/projects/)
* [REDCapR in CRAN](https://cran.r-project.org/package=REDCapR)
* [REDCapR in GitHub](https://github.com/OuhscBbmc/REDCapR)
* [PyCap](http://pycap.readthedocs.io)
* [REDCap FAQ](https://liberalarts.utexas.edu/redcap/help--faq.php)
* [REDCap Guide Microsoft](https://bioinformatics.rockefeller.edu/wp-content/uploads/REDCap_guide.pdf) Similar to above link

**Comment by kazoompa** [comment]
To complete this ticket must :
- [ ] add travis file
- [ ] use site.properties to customize settings
- [ ] review exceptions
- [ ] complete README

**Comment by ymarcon** [comment]
Done with release 2.12.0
