### ISSUE TITLE
SPSS (R) Export: Value Labels Missing

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3265]
If a variable only contains categories flagged as missing, the value labels are not included in the SPSS (R) export.

To reproduce:
1) Create a new table using the attached data dictionary "missing_value_label_dictionary.xls"
Note that all the categories for the 3rd variable are flagged as missing
![image](https://user-images.githubusercontent.com/34068523/43152131-9adc7e76-8f65-11e8-8f87-9bd5b272c110.png)
2) Import some dummy data using "missing_value_label_data.csv"
3) Export the file as SPSS (R)
4) View the exported file in SPSS
![image](https://user-images.githubusercontent.com/34068523/43151976-23d7bb24-8f65-11e8-932c-d02b2278ee68.png)
There are no category labels for the 3rd variable 

Provide there is at least one non-missing category the category labels all seems to export fine.

Is this an issue with Opal or the R plug-in?

[Missing_category_labels.zip](https://github.com/obiba/opal/files/2224497/Missing_category_labels.zip)

**Comment by ymarcon** [comment]
This was done on purpose to be consistent with the "labelled" R class as these categories do not describe all the possible values:
https://github.com/obiba/opal/blob/master/opal-r/src/main/java/org/obiba/opal/r/magma/VectorType.java#L370

Do you think the `areAllCategoriesMissing` criteria should be removed? what would be the effect on the resulting tibble?

**Comment by sam-story** [comment]
Thanks Yannick,

We have quite a lot of variables that store an exact measurement (height, weight, etc). We don't use categories for the positive values (as there could be 100's), but still want to record the different reasons why a measurement is missing. In these scenarios all the categories are missing.

I don't have a java development environment set up, is there an easy way for me to remove the areAllCategoriesMissing criteria, in the source code.
I'm happy to do some testing on the impact this has on the tibble export.

**Comment by ymarcon** [comment]
I have imported your provided test data into opal and assigned this table in R as a tibble (just like opal does before calling haven for SPSS export):

```
opal.assign.table.tibble(o, 'spss_export_test', 'demo.spss_export_test', missings = TRUE)
spss_export_test <- opal.execute(o, 'spss_export_test')
```

The resulting `spss_export_test` has the following structure in RStudio:

![image](https://user-images.githubusercontent.com/2581149/43208015-a9310e00-9029-11e8-8d77-0bafdd3c4551.png)

And the R summary is:

```
> summary(spss_export_test)
      id            no-missing-categories mixure-categories only-missing-categories only-negative-categories
 Length:4           Min.   :1             Min.   :1         Min.   :1               Min.   :-1              
 Class :character   1st Qu.:1             1st Qu.:1         1st Qu.:1               1st Qu.:-1              
 Mode  :character   Median :1             Median :1         Median :1               Median :-1              
                    Mean   :1             Mean   :1         Mean   :1               Mean   :-1              
                    3rd Qu.:1             3rd Qu.:1         3rd Qu.:1               3rd Qu.:-1              
                    Max.   :1             Max.   :1         Max.   :1               Max.   :-1   
```

**Comment by sam-story** [comment]
Hi Yannick,

Thanks for looking into this. I'm not clear what these results mean.

I can see that the structure of the only-missing-categories is different (doesn't have the attribute labels or names).

Does this mean that even with the areAllCategoriesMissing criteria removed, the R "labelled" class is still ignoring the value labels?

Is the labelled class part of haven? If so, I would be interested to find out if this is by design or a bug.

**Comment by ymarcon** [comment]
When removing the `areAllCategoriesMissing` criteria, the R "labelled" class is applied but this class is only supported by `tibble` type dataframes... Applying such a class on standard `data.frame` assignment (which is the default behavior of `opal.assign()`) will result in a error. This is a bit of work in Opal but it should be able to process the request appropriately.

**Comment by ymarcon** [comment]
Could you tell if this exported SPSS file has the expected format? 
[Missing_category_labels.zip](https://github.com/obiba/opal/files/2228596/Missing_category_labels.1.zip)

**Comment by sam-story** [comment]
Yes, the exported SPSS file is what I would expect. 
I haven't tested this yet with the STATA and SAS exports, are these likely to have the same issues, and would the fix in Opal resolve it for all R export formats.

Many thanks,

**Comment by ymarcon** [comment]
If the `tibble` dataframe built by opal is ok, it's the [haven](https://github.com/tidyverse/haven) package that handles the rest of the process (SPSS, Stata etc.).
