### ISSUE TITLE
mongodb/mysql ssl config issue

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3268]
It does not seem possible to configure Opal to connect via SSL to both a MongoDB and MySQL store in the same instance.

1) If the MongoDB is installed on a seperate server and the SSL mode is set to requireSSL, then it appears that the internal Opal keystore does not provide the SSL certificates in a format that is acceptable to MongoDB. We use [Jisc](https://www.jisc.ac.uk/) as our certificate Authoriser and as they are an intermediary provider, this requires the server certificate and intermediate certificate to be concatenated together. This can be worked around by creating a seperate Java keystore and importing the files in the required format and then referencing the new keystore in the Opal JAVA_ARGS. The steps I followed to create a seperate java keystore are [here](https://makandracards.com/jan0sch/24553-import-private-key-and-certificate-into-java-keystore)

2) If a seperate keystore is provided in the JAVA_ARGS the SSL connection to MySQL fails. The MySQL SSL connection works if there is no keystore is provided in the JAVA_ARGS and the certificate and key has been imported into Opal via the Opal UI.

A quick fix might be to specify the Keystore information as an advanced option when registering the database. The ideal solution would be to enable both Mongodb and MySQL to use the internal Opal keystore.

**Comment by ymarcon** [comment]
FYI the java keystore that is handled by opal application is not a file, it is persisted in the internal databases (orientdb).

**Comment by ymarcon** [comment]
Mongo Java Client is to be provided with a Socket Factory that is based on the Opal internal Key Manager.

**Comment by ymarcon** [comment]
The socket factory that is passed to mongodb java client, uses the opal system keystore as the key manager and opal credentials keystore (+default jvm trust store) as the trust manager.
