### ISSUE TITLE
Google Sheets datasource plugin to import data

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3283]
Use the java client that implements the [Google sheets API v4](https://developers.google.com/api-client-library/java/apis/sheets/v4) to read and write the (meta)data in Google sheets. The sheets format is the same as the one of the Excel datasource: variables, categories + one table per dataset.

**Comment by kazoompa** [comment]
Needs a little more info about _one table per dataset_. Do you mean a sheet can represent the data of a table?

Variables | Categories | TableA | TableB | ...

**Comment by ymarcon** [comment]
Exactly: *one sheet per opal table*

**Comment by ymarcon** [comment]
Replaced by #3313

**Comment by ymarcon** [comment]
Using #3313 and the R package mentioned in the previous comment, import GS table(s).

**Comment by ymarcon** [comment]
Packages initialization fails:

```
Loading required package: gargle
Downloading GitHub repo r-lib/gargle@master
These packages have more recent versions available.
Which would you like to update?

1:   mime (0.5   -> 0.6  ) [CRAN]
2:   R6   (2.2.2 -> 2.3.0) [CRAN]
3:   CRAN packages only
4:   All
5:   None

Enter one or more numbers separated by spaces, or an empty line to cancel
✔  checking for file ‘/tmp/RtmpTlms2h/remotes5a4c30d404dc/r-lib-gargle-3194ff5/DESCRIPTION’ ...
─  preparing ‘gargle’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘gargle_0.0.0.9000.tar.gz’
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/var/lib/rserver/R/library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘debugme’ is not available for package ‘gargle’
* removing ‘/var/lib/rserver/R/library/gargle’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpTlms2h/file5a4c6d9dc1bb/gargle_0.0.0.9000.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘googledrive’
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rematch2’
3: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘devtools’
4: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘gargle’
```

**Comment by ymarcon** [comment]
Missing useful options:

* skip
* na

**Comment by ymarcon** [comment]
Column types asks for the type of the ID column (for instance ID + 10 variables requires to specify 11 column types `Error : Length of col_types is not compatible with columns found in sheet:...`). This should not be necessary, so make sure you prepend "c" for the ID

**Comment by ymarcon** [comment]
`col_types` option is not necessary (as the guessing functionality is good enough). Please remove it and add the missing options `na` and `skip`.

**Comment by ymarcon** [comment]
Please sanitize the arguments:

* if the string that is passed has a ', make sure it is escaped.
* if a comma separated vector of strings is expected, make sure it is what it pretends to be.
* make sure it is a google valid sheet url or ID

**Comment by kazoompa** [comment]
The last request is easy since the spreadsheet metadata provides the list of sheet names. As for the ID, this will require a function as I had proposed in my email.

**Comment by kazoompa** [comment]
Sanitization is done in the plugin code. As for the ID and sheet name validation, invalid values are already caught by the current exception handlers.

**Comment by ymarcon** [comment]
If there is a malicious R code provided in the spreadsheet ID/URL field, it will be evaluated before the googlesheets4 raises an error. Then please do not let user entries go without checks. For instance instead of entering `1Hu9hZGa44mnwqnW21A-IDMAXobPiWJMVdzXxC6xLpHg`, a user could enter `1Hu9hZGa44mnwqnW21A-IDMAXobPiWJMVdzXxC6xLpHg'); print("coucou");c('` => some R code could be executed...
