### ISSUE TITLE
Importing/Exporting Missing Flags and Values

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3295]
There is an issue that category values flagged as missing can't easily be mapped from Opal to SPSS (and Stata or SAS). I have been looking at the tidyverse documentation and I think there are a few options we could consider for improving this.

The Problem
Opal allows any number of category values to be flagged as missing (e.g. -1 = Not answered, -2=not attended, -9999=withdrawn)

![image](https://user-images.githubusercontent.com/34068523/45052161-ea1d7600-b07d-11e8-948f-09065c17160d.png)

SPSS allows up to three category values to be flagged as missing or it allows one consecutive range and one discrete value.
![image](https://user-images.githubusercontent.com/34068523/45052191-fdc8dc80-b07d-11e8-832b-e75170edb075.png)

When Opal exports to SPSS the missing flags are not exported.
![image](https://user-images.githubusercontent.com/34068523/45052217-133e0680-b07e-11e8-88e1-e5bb70862b02.png)
If we don't put the missing flags back in then it makes it hard to do calculations like show me the frequency of all non missing values, rather than using the Missing keyword the user would need to look up and code each of the missing categories

The Workaround
We have a work around where we apply an SPSS syntax file to the downloaded file from Opal. This adds a Missing range of -9999 to -1 for all numeric variables except those in a lookup list. This is manageable in the short term but not a great solution.

The R Documentation
This is a known issue and is described on the tidyverse site https://haven.tidyverse.org/articles/semantics.html#missing-values

The SPSS Options
I have mainly been focusing on the SPSS options as this is the main package we use.
Step 1) When doing an SPSS export for each variable check the count of the categories flagged as missing. If there are three or less categories flagged as missing use labelled_spss to set them as distinct values. 
Step 2) If there are more that three categories flagged as missing do the following:
    Get the value of the highest missing category and the value of the lowest missing category 
    Get the value of the highest non-missing category and the value of the lowest non-missing category 
    Check if there is an overlap between the range of missing values and non-missing values. If there is no over lap then it is safe to use labelled_spss to set the range.
If there is an over lap then the easiest thing to do is to not export the missing info as is currently done (I would be happy with this solution as it is a very unlikely scenario). However it would be possible to do further checks to set the extreme (highest and then lowest) as the single distinct value and see if the overlap no longer occurs.

The other option is to switch step 1 and 2 round and try to create a range by default and then try using distinct values if there is an overlap on the missing range and non-missing range.

It would also be useful to have an option when running the export to either fail and log error if there is an issue with the missing categories or to ignore the missing values and continue if there is an error.

**Comment by sam-story** [comment]
If the haven class "labelled_spss()" is used during the import process (as per issue 3296) and the missing range is stored as an Opal attribute then I think it will also be possible to use "labelled_spss()" during the export to recreate the range. 
This will probably be better than the options I have listed above.

**Comment by ymarcon** [comment]
See also the comments about the usage of the `user_na` parameters in #3296.

The failure that can happen with this parameter should be handled: currently it just fails without notice as you stated in [this comment](https://github.com/obiba/opal/issues/3296#issuecomment-420590453).

**Comment by ymarcon** [comment]
When calling `read_spss` with `user_na=TRUE` I am able to identify the missing categories using `na_values` attribute.

![image](https://user-images.githubusercontent.com/2581149/45496443-bb865600-b775-11e8-9464-ed1057182720.png)

I am not sure what to do with the `na_range` attribute as opal does not support "missing" ranges. Ignore it?

**Comment by sam-story** [comment]
We could store both the na_values and na_range in Opal as attributes (maybe give them a Namespace too). Then when doing an SPSS (R) export we have the option to use the na_values and na_range Opal attributes to create the labelled_spss() class in R. 

This would be simpler than the options I suggested above however if a user has changed the Missing flag in opal after the file was imported then the na_values and na_range will be out of date. Maybe it is better to ignore the na_range, and the recreate it using one of the options above at the point of export.
 
Note: although the documentation isn't very clear about using labelled_spss() with write_sav() I have tested it in R Studio and created a file .sav with missing values and ranges.

**Comment by ymarcon** [comment]
Import and export of missing categories and values now works with SPSS (except the unsupported range of missings).
I don't see any [tagged missing values](https://haven.tidyverse.org/articles/semantics.html#missing-values) in the data structure of the imported data (after converting the SPSS file into SAS and Stata using *haven*), so I could not implement any missings handler for Stata and SAS formats. Do you have example files in Stata and/or SAS with missing values?

**Comment by ymarcon** [comment]
The haven's NA tag things do no not work either with the missing_test example files. SAS read does not even report categories. If you can get an original Stata file, that would be great.

**Comment by ymarcon** [comment]
You can try [this snapshot RPM package](https://obiba.jfrog.io/obiba/rpm-local/opal-server-2.12-SNAPSHOT20180914084246.noarch.rpm).

**Comment by sam-story** [comment]
Here is a Stata file that one of our data team created.
[missing_test_Stata_with_missing.zip](https://github.com/obiba/opal/files/2383627/missing_test_Stata_with_missing.zip)

Missing numeric values are stored in the format ".a", ".b", ".c" etc with a label associate with each missing value.

**Comment by ymarcon** [comment]
The imported Stata variables with tagged missings are poorly described by the Rserve java library: all the different flavors of Na ends as being NaN (not a number) values. Data are correct but not the categories.

**Comment by sam-story** [comment]
I have tested the snapshot and have found a couple of issues.

1) When importing we do need to process $na_range to identify missing categories. This could be done by looping through each of the $labels and checking if the value is within $na_range
E.g. The attributes in R for variable-2 in the file label_tests_missing.sav:
> ltm <-read_spss("label_tests_missing.sav", user_na = TRUE)
> attributes(ltm$variable_2)
$label
[1] "variable_1 label"

$na_values
[1] 2000

$na_range
[1] -999  999

$class
[1] "labelled_spss" "labelled"     

$format.spss
[1] "F6.0"

$labels
             One      Two Missing    Three Missing      Not Missing Discrete Missing 
               1                2                3             1000             2000

Categories "One", "Two Missing", "Three Missing" can be set to missing by checking the value against na_range.  
Category "Not Missing" is not missing 
Category "Discrete Missing" is set by checking the value against na_values.

[label_tests_missing.zip](https://github.com/obiba/opal/files/2386476/label_tests_missing.zip)

2) The SPSS (R) Export fails if there are more than three missing categories. Rather than failing you could set $na_values = [Min Missing Category Value] " - " [Max Missing Category Value]
This should be simple to do and I think this will meet all of ALSPACS requirements however there are scenarios where this would lead to an incorrect definition being exported. There are some other solutions but they become more complex, might be best to discuss via a video call.

**Comment by ymarcon** [comment]
1. I thought that all values of *na_range* are missings but apparently discrete values from that range can be named and that makes categories with missing flags. This case will be handled.
2. Do you mean *na_range* in place of *na_values*?

**Comment by sam-story** [comment]
1. Great. Sorry this was a bit unclear.
2. Yes, na_range = [Min Missing Category Value] " - " [Max Missing Category Value]
If the user selects exporting using SPSS (R), I think there needs to be an on screen explanation of how na_range is being created from R. 
Are you planning to do the simple solution or one of the more complicated ones?

**Comment by ymarcon** [comment]
1. Implemented
2. Will build a range and an optional missing value from the set of missing categories.

**Comment by ymarcon** [comment]
You can try [this snapshot](https://obiba.jfrog.io/obiba/rpm-local/opal-server-2.12-SNAPSHOT20180917134902.noarch.rpm).

**Comment by sam-story** [comment]
This is great, I have tested the following scenarios and all exported successfully:
- Three discrete missing values seperated by non-missing
- Range of concurrent missing values
- Range of concurrent missing values with single low missing value seperated by non-missing
- Range of concurrent missing values with single high missing value seperated by non-missing

Multiple ranges or more than 3 discrete missing values fail as expected. If it is possible it would be useful for the log to record which variable caused the failure. 
![image](https://user-images.githubusercontent.com/34068523/45675742-ebdc4480-bb27-11e8-9e4c-5086ba2cc995.png)
Our tables have 100's of variables in so it would be difficult for the user to identify which one has caused the failure. However this error is unlikely to occur so this is not a high priority.

Also when I tested importing categories for text/string variables, I have noticed that R does not populated them in labelled_spss(). This would need a change to haven to fix. I don't think it will be an issue for us, but may cause problems for other users.

**Comment by ymarcon** [comment]
Thanks for the tests. It's *haven* that raises a write error when there are multiple *na_values* with one *na_range* without specifying which variable is the cause. Opal can only log a warning (because the tibble that is built is the same for all file formats).

**Comment by sam-story** [comment]
This functionality no longer works in Opal 2.14.

When the attached file "missing_tests_SPSS.sav" is imported into Opal all the missing categories are set up correctly, but after exporting as SPSS format there are no categories or missing values in the export file:
![image](https://user-images.githubusercontent.com/34068523/60586774-b210bd80-9d8a-11e9-9ef0-019c4dde6fd2.png)

Also when the file "range_issue.sav" is imported and then exported. The following error appears in the Opal log:
_2019-07-03 12:18:18,741 [pool-4-thread-1] WARN  org.obiba.opal.r.datasource.RAssignDatasource - Variable variable_1: SPSS format does not support more than one discrete missing value in addition to a missing values range._

However I have checked the data and it fits within a range and one discrete value, and the same variable exported fine in version 2.13 and the data has not changed.

Let me know if you need any more info,

[SPSS export missing issues.zip](https://github.com/obiba/opal/files/3354810/SPSS.export.missing.issues.zip)
