### ISSUE TITLE
Values truncated using SPSS Import

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3296]
When importing using SPSS, numeric values are truncated based on the precision of the Decimal variable setting in the SPSS file. The Decimal setting is a display setting and often the value stored has a larger number of decimal places. this means that Opal is losing the additional decimal places.

Is the IBM SPSS API used to do the standard SPSS import, is there an alternative setting that could be used to import the full value rather than the display value? If not one option would be to change all numeric variables to format F40.16 (the maximum) before importing, however it would be useful to retain the original format for the opal attributes e.g
![image](https://user-images.githubusercontent.com/34068523/45163036-4354e900-b1e7-11e8-8ed2-1d8865429c13.png)

 
To recreate import the following CSV structure into SPSS and saved as a .sav file

```
id,ten_decimals,three_decimals
1,10.1,10.1
2,10.123,10.123
3,10.12345,10.12345
4,10.1234567,10.1234567
5,10.123456789,10.123456789
6,10.1234567890123,10.1234567890123
```

Set the variable details as below
![image](https://user-images.githubusercontent.com/34068523/45163072-5b2c6d00-b1e7-11e8-8fd4-9d043fc4061f.png)

When importing using SPSS, the data will be imported like
![image](https://user-images.githubusercontent.com/34068523/45163099-6b444c80-b1e7-11e8-95c1-c26c57e1e43a.png)

When importing using SPSS (R), the full value is imported and there is no loss of precision. See
![image](https://user-images.githubusercontent.com/34068523/45163141-8747ee00-b1e7-11e8-85b5-d36e90de6a42.png)

**Comment by ymarcon** [comment]
Have you used the R based SPSS importer?

**Comment by ymarcon** [comment]
Could you provide the sav file with the Decimal setting that truncates the displayed value?

**Comment by ymarcon** [comment]
The "standard" SPSS importer (which I would rather call "legacy" because it is based on a SPSS reader java library that is not maintained anymore) will be decommissioned from Opal in the next release. It will be moved to a "datasource" plugin, still usable in Opal but not delivered with the core datasources. Instead of that, the R-based datasources will be preferred because these are using a reliable library [haven](https://haven.tidyverse.org/). If any problem is encountered, it may be relevant to file an issue on the *haven* package instead: Opal only reads the R data frame (tibble) that is produced by this library.

**Comment by ymarcon** [comment]
@kazoompa Can you check if it is the [spssreader](https://github.com/obiba/spssreader) or the [opal-datasource-spss](https://github.com/obiba/opal-datasource-spss) that does the rounding of the values according to the Decimal setting?

**Comment by sam-story** [comment]
I have been investigating the SPSS (R) issue 1 from above.
I was mistaken in thinking it was not importing negative numbers, it is actually not importing Missing values, the default for read_spss() is to set SPSS missing values to NA. 

There is a parameter "user_na" which can be set to True to allow Missing values to be imported, e.g. read_spss(file, user_na = TRUE).  See https://github.com/tidyverse/haven/issues/33

When I tried using "d <- read_spss(file, user_na = TRUE)" the command executed but then I got an error when trying to view the data View(d)
Error: `x` and `labels` must be same type

I've never used R before and don't know if this is a common error or something specific to this issue.

**Comment by sam-story** [comment]
As a follow on to the above when using user_na = TRUE there is a separate class "labelled_spss()" for labels in SPSS that will handle user defined missing ranges. This will be very useful for issue 3295.

**Comment by sam-story** [comment]
The SPSS (R) issue 2 from above seems to occur when a variable with Categories (opal terminology) has a value with decimal places. The process sets the Opal data type to Integer and then fails when a decimal tried to be imported.

See example .sav file
[precision_tests_r_issue2.zip](https://github.com/obiba/opal/files/2370776/precision_tests_r_issue2.zip)

Although you would't normally have categories with integer values Opal does support this functionality. Also we set up missing categories for all variables, including measurements that need multiple dp precision.

I suspect there is some code that sets the Opal data type to Integer if the variable has categories. If this is Opal code rather than R code then I would recommend this step is removed and the data type is set in the same way it is if the variable does not have categories.

**Comment by ymarcon** [comment]
You were right with your suspicion regarding the numeric type when there are categories:
https://github.com/obiba/opal/blob/2.11.2/opal-r/src/main/java/org/obiba/opal/r/magma/RVariableValueSource.java#L119-L123

The integer type was applied to have clean ordinal variables (have makes doubles even when not necessary). I will try to keep the decimal type but still make the category name look an integer ("1" instead of "1.0").

**Comment by sam-story** [comment]
Yes, I think this is a good solution to use doubles for the variables but make the category look like an integer.

I have been running some tests on our real data and they are importing fine using:
 df <- read_sav(file, user_na = TRUE)

I have attached an example file that works as well.
[label_tests.zip](https://github.com/obiba/opal/files/2374470/label_tests.zip)

I haven't worked out what was breaking in the previous example I sent but will continue to look into this. It seems to be something related to the data type of the categories being different to the data type of the values.

One think I haven't been able to understand how the labelled() and labelled_spss() methods work. All their examples are for creating the labels and I want to try and read them.

I have also tried to use:
_df <- read_sav(file)
attributes(df)_

to read the labels but I only get basic attribute information, e.g. 
$names
$row.names
$class

What code do you currently use in Opal to read in a .sav file and get the spss.format attribute and the category labels?

**Comment by sam-story** [comment]
The Error message _"Error: x and labels must be same type"_ occurs in R when you import a variable that has a missing range or value set but no categories set.

![image](https://user-images.githubusercontent.com/34068523/45418088-8d245000-b67b-11e8-8d71-6218ef7890af.png)

This is a valid error as you shouldn't really have a missing values that aren't related to a category. Although it might be better to catch this error in Opal and include a more descriptive error in the log.

**Comment by ymarcon** [comment]
Thanks for the `user_na` inspection, this is useful.
FYI we use the Rserve API to extract the attributes and categories of the R objects. See how the REXP object is handled:
https://github.com/obiba/opal/blob/master/opal-r/src/main/java/org/obiba/opal/r/magma/RVariableValueSource.java

**Comment by ymarcon** [comment]
The values are not truncated anymore when reading a SPSS file using the [SPSS datasource plugin](https://github.com/obiba/opal-datasource-spss).
When import is done through SPSS(R) core datasource, the numeric data type has been fixed.
See #3295 for the missing flags and values handling.

**Comment by sam-story** [comment]
I have tested the snapshot https://obiba.jfrog.io/obiba/rpm-local/opal-server-2.12-SNAPSHOT20180914084246.noarch.rpm and the precision issue appears to be resolved. There is still and issue with the missing flags and values handling, which I have recorded against #3295.
