### ISSUE TITLE
NA values issues when table imported from R to opal with 'opal.symbol_import' command.

### ISSUE THREAD

**Issue by asarr2** [obiba/opal#3303]
When we  import a table from R to Opal (version 2.11.1) ,by using 'opal.symbol_import' in R, 
the NA values are replaced randomly by huge numbers in Opal when the value Type is integer (seems normal when the value type is decimal).
Ex:
![image](https://user-images.githubusercontent.com/35842296/45907564-67f3b800-bdc6-11e8-83a3-bd5387f6cee5.png)
In this example, the value -2147483648 was supposed to be an NA.

The table used for the example is attached . 
[test_opal_import.xlsx](https://github.com/obiba/opal/files/2407122/test_opal_import.xlsx)

**Comment by ymarcon** [comment]
Opal imports tibbles. Could you share the tibble that is imported (or the script that reads the excel file you provided)?

**Comment by ymarcon** [comment]
I can reproduce the issue using this R script:

```
library(opal)
library(tidyverse)
# generate a tibble with NA integers
cols <- 2
rows <- 10
tb <- as_tibble(data.frame(replicate(cols,sample(0:5,rows,rep=TRUE))))
tb$X1[3] <- NA_integer_
tb$X1[5] <- NA
tb$id <- seq(1,10)
is.na(tb$X1)
# upload tibble in a remote opal R session
o <- opal.login("administrator","password", "https://opal-demo.obiba.org")
opal.assign(o, "tb", tb)
opal.execute(o, "is.na(tb$X1)")
opal.symbol_import(o, "tb", "datashield")
opal.logout(o)
```
