### ISSUE TITLE
Import fails if file named "n.sav"

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3315]
When importing a file using SPSS (R) the import fails if the file is named "n.sav" (see attachment). It will import correctly with any other filename. I have tested with three completely different files and all failed when named n.sav.

The error displayed on screen is:
org.obiba.opal.r.MagmaRRuntimeException: Error in n[[n]] : subscript out of bounds

I haven't tested if this also happens with other import formats.

[n.zip](https://github.com/obiba/opal/files/2478164/n.zip)

Opal version 2.12

**Comment by ymarcon** [comment]
The SPSS file is read in a tibble accessible by the symbol "n" (the file base name), and this symbol conflicts with the scripts that extracts the class, type, attributes etc. from the columns. Will make sure there is no conflict in this generated code.
