### ISSUE TITLE
Rectangular format datasource plugin to import data

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3318]
This is to be based on the [readr](https://readr.tidyverse.org/) R package as specified in #3313.

Implement from the project: [opal-datasource-readr](https://github.com/obiba/opal-datasource-readr)

There are several read functions in the [readr documentation](https://www.rdocumentation.org/packages/readr/versions/1.1.1):
* delimiter separated reader: [read_delim](https://www.rdocumentation.org/packages/readr/versions/1.1.1/topics/read_delim) 
* white space separated reader: [read_table](https://www.rdocumentation.org/packages/readr/versions/1.1.1/topics/read_table)

The import options should allow to switch between these 2 readers and their associated options.

**Comment by ymarcon** [comment]
What this default value mean? 

![image](https://user-images.githubusercontent.com/2581149/47674719-3eddf880-dbb8-11e8-9f0d-4bb8042ce287.png)

**Comment by ymarcon** [comment]
Delimiter character default should be ,

**Comment by meek0** [comment]
`.default` represents all columns. It can be omitted but it seemed to be a simple example on how to use this field.

I could leave it blank and explain that if one specifies the colum types, it must be done for all columns unless subset is checked.

**Comment by ymarcon** [comment]
You should parse the entry: key-value, comma separated. If .default key is missing, add it. Default input is empty. Give an example in the description of the field.

**Comment by meek0** [comment]
.default="?" is only an example, if one does not check "Subset of Columns" one must provide all other the type for all columns.

**Comment by meek0** [comment]
`skip` seems to cause problems: The header line will not be read if you skip it.

**Comment by ymarcon** [comment]
Of course but sometime the header is not at line 1, thus the usefulness of this option.

**Comment by ymarcon** [comment]
The `.default` example is cryptic and should be in the description instead. 
The column types should be as simple as it is in googlesheets4: cnnicc should be a valid input (forget the key-type map)
I don't think "subset of columns" should be necessary.

**Comment by meek0** [comment]
For col_types, they are all valid. Subset is only using cols_only vs cols where cols_only is the subset.

**Comment by ymarcon** [comment]
`col_types` option is not necessary (as the guessing functionality is good enough). Please remove it (with the subset option) et add the missing options `na` and `skip`.

**Comment by ymarcon** [comment]
Please sanitize the arguments:
* if the string that is passed has a `'`, make sure it is escaped.
* if a comma separated vector of strings is expected, make sure it is what it pretends to be.
