### ISSUE TITLE
Implement Analyses Web UI

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3370]
According to [mockups and specifications](https://github.com/obiba/opal/wiki/Analysis-Plugins)

**Comment by ymarcon** [comment]
Errors:

* ``View`` does not show parameters
* ``Duplicate`` link does not duplicate parameters

**Comment by ymarcon** [comment]
The Date in the analysis list must be the date of the last result.

**Comment by kazoompa** [comment]
It is the creation date of the _last_ result.

**Comment by ymarcon** [comment]
@kazoompa currently it's the creation date of the analysis, not of the last result.
