### ISSUE TITLE
Project dropdown resets when creating a view from the cart

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3393]
If a view is created from the shopping cart and it has a large (~3000) number of variables, the project drop-down keeps resetting.

![image](https://user-images.githubusercontent.com/34068523/49817802-1fb2b900-fd69-11e8-990d-ee4fe1dea7f9.png)

Selecting an item from the drop down or typing in values will continually be reset to the default project for a period of time.

The more variables there are in the view the longer the resetting goes on for. In this instance it took 2 minutes before the project I selected was not reset.

If the screen is doing some processing in the background it would be useful to disable the control until it's ready.

**Comment by ymarcon** [comment]
Looks like the onReveal() method where the project list is retrieved is called multiple times.
