### ISSUE TITLE
Improve performance of table to R data.frame/tibble assignment

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3405]
The performance issue (that can be observed on very large tables) is due to the fact that the databases (mongo or sql) are row oriented while R data frames are column oriented. To make things easier, opal reads all the rows of the table to build all the the columns (vectors) *in memory* and push them to R (one by one). Then these vectors are bound in a data frame. Doing this in-memory allows to read the data from the database efficiently and to bind vectors as a data frame efficiently as well. But in the case of a large dataset, that does not work. Increasing the RAM is the only way to do that currently. 

One possible improvement would be to find a way to merge R data frames by rows. Maybe using [base::rbind()](https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/cbind) or [dplyr::bind_rows()](https://dplyr.tidyverse.org/reference/bind.html) would do the trick. Be careful that the tibble resulting of the merge has all the attributes (labels etc.).

Large table export issue reported by @sam-story

**Comment by ymarcon** [comment]
@sam-story What would you be the size of the tables in terms of data points (rows x columns)? I have different test datasets: 100K x 10, 1350K x 28, 16600 x 16800... What would be realistic ones for your?

**Comment by sam-story** [comment]
Our tables all contain ~ 16,500 rows (participants). We have several tables with >2,000 columns (variables). Our largest table has approx 2,800 variables.

Most of the variables are decimals with a small number of text.

**Comment by ymarcon** [comment]
The purpose of this issue is to make data export/assignment to R more memory efficient: large tables that could not be exported because of Opal not having enough memory space will be supported.

**Comment by ymarcon** [comment]
This affects the plain R assignment and the R assignment when exporting data using a R exporter (either builtin (haven) or provided by a plugin (readr etc.)).
