### ISSUE TITLE
Projects screen loading time

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3417]
When loading the main project list screen Opal also retrieves a list of all the tables in each project. However this data is not used.

![image](https://user-images.githubusercontent.com/34068523/50902736-9c41c180-1413-11e9-95c9-8fe983645148.png)

When there are lots of projects with lots of tables the screen can take several seconds to load. 

Update the code so that the list of tables is not retrieved.

**Comment by kazoompa** [comment]
We can simplify this API to get a more specific response.

**Comment by ymarcon** [comment]
Fix does not solve the problem as the project's timestamp is still extracted from the union of the tables' timestamps, which can be an expensive operation when there are many of these.

**Comment by ymarcon** [comment]
Events that must trigger the project last update timestamp:
* adding a view
* editing data dictionary

**Comment by ymarcon** [comment]
#3428 to be done first.
