### ISSUE TITLE
Harmonisation scripts with larger number of variables cause projects screen to not load for systems using SQL databases

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3423]
Certain harmonisation scripts can cause the projects page to not load on systems using SQL-like databases:

![image](https://user-images.githubusercontent.com/8521654/51040154-a1874380-15ae-11e9-93ea-83cc9afab152.png)

This can be replicated by using this data: [G10Kx50.zip](https://github.com/obiba/opal/files/2749959/G10Kx50.zip)

Then, generate a view with an integer variable called test. Enter the following script:

`$('X1')+ $('X2')+ $('X3')+ $('X4')+ $('X5')+ $('X6')+ $('X7')+ $('X8')+ $('X9')+ $('X10')+ $('X11')+ $('X12')+ $('X13')+ $('X14')+ $('X15')+ $('X16')+ $('X17')+ $('X18')+ $('X19')+ $('X20')+ $('X21')+ $('X22')+ $('X23')+ $('X24')+ $('X25')+ $('X26')+ $('X27')+ $('X28')+ $('X29') +$('X30')`

If the final `+$('X30')` is omitted, no problem is seen

**Comment by ymarcon** [comment]
Fix in magma 1.18.4
