### ISSUE TITLE
SPSS (R) export must format dates to what SASS accepts

### ISSUE THREAD

**Issue by kazoompa** [obiba/opal#3434]
**Describe the bug**
Opal dates are in  ISO_8601 format (yyyy-MM-dd) which is not a date format that SPSS accepts.

**To Reproduce**

Import a CSV that looks like:

|entity_id |Name |Gender |Date|
|----------|:----------|-------|:---------|
|Y00B21|Carlos |1 |2018-07-04|
|Y00B23|Santiago|1 |2018-07-10|
|Y00B25|Maria |0 |2018-07-11|

Export the table using the SPSS (R) option

Open the SAV file in SPSS

The error is that none of the date values are imported, instead they're all empty.

**Expected behavior**
All dates values are valid and are of Date type

**Comment by ymarcon** [comment]
When exporting in SPSS (R), opal makes a R tibble and then call [haven](https://www.rdocumentation.org/packages/haven). The opal `date` type is turned to [`Date` class](https://www.rdocumentation.org/packages/base/versions/3.5.2/topics/Dates) in R. Whether haven handles the `Date` class correctly, that's the question.

A lower level example, using R, something like:

```
library(opal)
o <- opal.login()
opal.assign.table.tibble(o, "D", "test.Dates")
D <- opal.execute(o, "D")
opal.logout(o)
D
class(D$Date)

library(haven)
write_sav(D, "Dates.sav")
D2 <- read_sav("Dates.sav")
```
