### ISSUE TITLE
Project default settings

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3438]
- [x] **Export folder** 

Currently the default export destination in the UI is in the user's folder `/home/$USER/export`. It should be possible to specify a default destination folder per project `/projects/$PROJECT/export`. 

- [x] **ID mapping**

It should be possible to have a default ID mapping (per entity type?) that would be used both at import and export (suggestion, not enforced selection). When an ID mapping is removed, the project settings should be updated accordingly.

(from @sam-story)

**Comment by sam-story** [comment]
At t he moment we only have the need to have one value for the default ID. If the default doesn't exist for the selected entity then no default mapping is selected (e.g. as per existing functionality).

However if it's easy to add we could use enter a YML structure to specify a default per entity, e.g.
Participant: collab-mapping1
Sample: standard-mapping
...

any errors would just go back to having no default.

**Comment by ymarcon** [comment]
This will not be a configuration file, this will be added to the UI for editing the project's settings.

**Comment by sam-story** [comment]
Okay, lets just go with a single text box. On export if a mapping exists with the default mapping value for the given entity then set the mapping to that. If not leave it as no mapping.
The user can then set it to whatever they want

**Comment by ymarcon** [comment]
Note: project default export folder should be passed to export plugins, currently this is not the case.
