### ISSUE TITLE
Extract only needed values when executing view scripts

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3440]
Currently when executing a script, the complete value set of the joined tables is extracted. Can be 1000 values despite only one is needed. Parsing the script could narrow the set of variable values to be extracted. But what about the generated accessors? (when iterating other a list of variables like VAR1, VAR2, ...):

```
for (i=1; i<=10; i++) {
  var value = $('VAR' + i);
  // do somtething with value i ...
}
```
(from @sam-story)

**Comment by sam-story** [comment]
This does significantly increase the potential complexity of this change.

Options I can think of are:
1. Evaluate the script as part of the parsing process to ensure generated accessors names are returned. This could introduce lots of unforeseen issues and I expect would be a lot of work, however it would be the most complete option.
2. Have a user setting on a per view basis to select if the script is parsed before export. Accept that the export would fail if parsing is selected and generated accessors are included.
3. Improve the performance of exporting fully qualified variables that are not in the referenced tables. Pre-parse fully qualified variables group them on datasource and table and then make one data request per table.  Don't pre-parse variables that aren't fully qualified. This doesn't remove the issue (e.g. fully qualified generated accessors would still fail) but it does give the user more options, however setting up lots of fully qualified variables is not easy through the UI and would only be efficient for users creating then via the API.

I think my preference is for option 2. However things could still get complicated when creating nested views some of which are flagged to be parsed and some not. Debugging a view that failed could be difficult and the error log would need to specify which datasource.table:variable had caused the export failure.
