### ISSUE TITLE
Support SAS transport files read and write

### ISSUE THREAD

**Issue by kazoompa** [obiba/opal#3442]
There are the following limitations:

- variable should not contain '-'
- the table name cannot be more than 32 characters and should only include:
   - characters
   - numbers
   - underscore

There is a chance the Haven library does not produce correct regular SAS files, one possible workaround is to generate the open-format **xpt** or an Opal plugin that permits choosing Haven or another library for exporting to SAS.

May be Opal should not permit variable names containing '-'.

**Comment by ymarcon** [comment]
Try to reproduce with haven directly. You can see in the opal log the R commands that are executed.

**Comment by ymarcon** [comment]
If you can reproduce the error with haven directly, please close this issue ad open one in https://github.com/tidyverse/haven/

**Comment by ymarcon** [comment]
See [Read and Write SAS Transport Files](https://www.rdocumentation.org/packages/haven/versions/2.1.0/topics/read_xpt).
