### ISSUE TITLE
Refreshing a Project Datasource

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3453]
This a new feature request and may be a duplicate of #2038

We have set up a project that uses the id mapping at it's datasource, this is useful as it give us more control over permissions (e.g. we can give non-administrators view permissions on specific mappings).

The problem is that when a new mapping is added through the administrator functionality the project does not automatically pick up the new variable. You either need to restart Opal or archive the project and reinstate it.

We would like the option to be able to refresh a project datasource from the project admin page or via a rest api call.

**Comment by meek0** [comment]
It seems that a "project refresh" would have to be a command. That way it could be queued in the task scheduler and a state would not really be needed.

**Comment by ymarcon** [comment]
@meek0 While the datasource is being refreshed (whether in a task or not) it must not be accessed for writing (and also for reading I guess). Thus the project state.

**Comment by ymarcon** [comment]
@meek0 after testing there are some issues.

1. User with limited permissions receives a permission error:

![image](https://user-images.githubusercontent.com/2581149/57940705-5b7c1c80-78cd-11e9-83ca-3dde32d1bc6c.png)

2. In addition to that ``state`` is a sub-resource of project, not of its commands: ``/project/<name>/state``. The reason of that is while the project's datasource is being refreshed, the GUI should check that ``/datasource/<name>`` will not fail:

![image](https://user-images.githubusercontent.com/2581149/57941097-4227a000-78ce-11e9-9010-d57f2a3b3b2d.png)

3. You must add some help text that describe what are the implications of refreshing a project:

![image](https://user-images.githubusercontent.com/2581149/57941203-99c60b80-78ce-11e9-9ff4-6fc4d6b8e0fa.png)

> Refreshing a project makes its data temporarily inaccessible (no table listing, no import or export) while the connection to the database is being re-initialised. The time taken by this operation depends on the database type and schema.

**Comment by ymarcon** [comment]
Still not working for a user having "Administrate" permission on "All tables":

![image](https://user-images.githubusercontent.com/2581149/59058570-39a70180-889d-11e9-9c19-ec972f00630d.png)
