### ISSUE TITLE
Option to include checksum digits to generated id mapping

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3454]
- add the ability to generate IDs with the Luhn checksum appended.
- capture additional ID mapping generation options (checksum, delimiter) from web UI.
Exclusions:
- internal opal IDs are not generated with this checksum 
- no checksum validation is required at importation time

**Comment by ymarcon** [comment]
The UI will propose to generate identifiers with 2 different methods:
* random ID, with size, leading 0s and prefix parameters (current form),
* OR a random ID that is Luhn valid (see [LuhnValidator class](https://github.com/obiba/opal/blob/master/opal-core/src/main/java/org/obiba/opal/core/tools/LuhnValidator.java)).
