### ISSUE TITLE
Use option to compress SPSS files on export

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3455]
SPSS files that are created by R are hugely bloated (around ten times larger).
 
The Haven write_sav function has an option to compress files (https://haven.tidyverse.org/reference/read_spss.html). 

The compressed files type (.zsav) was introduced in SPSS version 21 (released in 2012) and is now supported for importing into other Stats packages (SAS, STATA).
https://pspp-users.gnu.narkive.com/IToYTzIz/zsav-format-support-zcompressed-subcommand

.zsav files can still be saved as .sav files and will be opened correctly as the header information is the same.

It would be nice to have an API and UI option to set compress to true when exporting SPSS files. Having a default system setting would also be useful.

**Comment by ymarcon** [comment]
Files with .zsav format can be imported/exported using UI and related python command.
