### ISSUE TITLE
Backup and Restore view from GUI

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3464]
It is currently possible to backup views in JSON format files and restore them using the [backup-view](http://opaldoc.obiba.org/en/latest/python-user-guide/datasources/backup-view.html) and [restore-view](http://opaldoc.obiba.org/en/latest/python-user-guide/datasources/restore-view.html) python commands. The purpose of this task is to allow the same operation from the GUI, datasource page. The web services to be used are the same.

The new action menu are, from the datasource page:

* **Download > Backup view** (right after the Download view menu entry)
* **Add Table > Restore view...** (right after the Add view menu entry)

Just like the python command, the view name does not need to be specified as it is part of the JSON object. Then, restoring a view will propose the form:

* select the JSON file:
  * either from the opal filesystem,
  * or from a local file (?).
* select option to force overwrite (default is no), ideally the content of the JSON file should be read to identify any name conflict.

**Comment by ymarcon** [comment]
* refresh table list after restore
* there is a  js console error despite the view restore was successful:

```
zbd {f: "Error parsing JSON: SyntaxError: Unexpected token )↵", g: null, __gwt$backingJsError: Error: Error parsing JSON: SyntaxError: Unexpected token )

    at oZ.lZ [as Kf] (ui-0.js:12775:26)…}
``` 

* have you updated opaldoc (dev branch)?

**Comment by meek0** [comment]
still need to hide backup button if views are empty and update opaldoc

**Comment by ymarcon** [comment]
Note: implementation restores from local file only.
