### ISSUE TITLE
Locale attributes and Referenced Entity Type not modified on merge dictionary import

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3470]
When updating variables using the "Add/Update tables from dictionary" functionality if the "merge the variables" option is selected certain properties (Referenced Entity Type and local language attributes) are omitted.
![image](https://user-images.githubusercontent.com/34068523/58088236-17816400-7bba-11e9-857d-130b7c464960.png)

To reproduce:
Import the attached dictionary into an Opal project. Manually edit the aln variable through the UI and remove all advance properties (Unit, Referenced Entity Type, Mime Type, Index) and attributes (legacy, Mlstr_area)

 Now reimport the dictionary file again making sure "merge the variables" option is selected.

The "Referenced Entity Type" property is not imported and the local (en) value for the legacy attribute is not imported.
Note; yhe process works fine if the  "merge the variables" option is not selected.

**Comment by sam-story** [comment]
Test file:
[test.cp-dictionary.xlsx](https://github.com/obiba/opal/files/3202049/test.cp-dictionary.xlsx)

**Comment by ymarcon** [comment]
Already fixed.
