### ISSUE TITLE
Improve performance of CSV import

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3471]
As reported by @sidohaakma Opal struggles at importing a CSV file with 20M of rows.

After inspection, the CSV datasource loads all the file in memory in a hashmap in order to be able to read data in a random order (and then scanning file only once). This works well for small datasets, but requires too much memory for larger ones. A different strategy is to be found.

**Comment by kazoompa** [comment]
A possible file reading strategy: https://dzone.com/articles/how-to-read-a-big-csv-file-with-java-8-and-stream

**Comment by ymarcon** [comment]
Reading CSV format is much more complex than just a String.split (can be on mulptiple lines, there are escape chars etc.). The problem is more about the sequential reading of file that does not fit with our datasource API. I think I am going to cache the lines only for preview (data import), then will go for copying with the identifiers in the same order as they appear in the file.

**Comment by ymarcon** [comment]
See also #3405
