### ISSUE TITLE
Report Improvements

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3477]
Three suggestions for improving reports.

1) Restrict the location of the Report template file location 
![image](https://user-images.githubusercontent.com/34068523/58545946-41f7a080-81fc-11e9-8158-d2e680ccc4bf.png)
.Rmd files should only be allowed in a location accessible by the report administrators. The Reports file structure could be extended for this purpose and for each project in the reports folder create a restricted /rmd sub folder e.g. only users with Report administrator permissions for the project have write access to the "fs/reports/[project name]/rmd" folder.

2) Create a third permission "Execute reports", allowing a user to execute reports but not change any settings
![image](https://user-images.githubusercontent.com/34068523/58546372-19bc7180-81fd-11e9-8359-0ea16428fed9.png)

3) Extend the functionality of the "Execute report" permissions to edit certain Options.
![image](https://user-images.githubusercontent.com/34068523/58546533-76b82780-81fd-11e9-8be8-e6c91b679605.png).
These users are not able to Add or Delete Options, but Administrator user is able to configure some options as editable and users with Execute report are able to edit this Options only.

**Comment by sam-story** [comment]
Items 1 or 2 are related to a security issue.   

A normal report user must not be able to change the R markdown file location, or have permission to over-write an existing .Rmd file.

The quickest fix is probably option 2 which allows people to run reports but not change any parameters, and then to have some onscreen help text that says.
"If you do not want normal users to edit your .Rmd file, make sure it is saved to a folder that normal users are not able to access."

**Comment by sam-story** [comment]
Additional security issue. See email on 25/07/2019, for more details

**Comment by ymarcon** [comment]
Reports feature is deprecated
