### ISSUE TITLE
Help users avoid data import failure from SAS/SPSS/Stata

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3493]
**Problem:**

Users get frustrated when they import their data from a native format like SAS/SPSS/Stata and the import fails or the data type is changed (for example, sometimes integers get changed to decimal, or integers to factors). I understand that there might be limited control we have over this in Opal because it is relying on the behaviour of the tidyverse package.

**Potential solution:**
Investigate how tidyverse behaves with different datasets. Development of a checklist to understand the likely behaviour when these datasets are read in using tidyverse. Ultimately this could be coded into SAS/SPSS/Stata code to run on their data to 'clean' it into a format that will be reliably interpreted by tidyverse, before trying to import it into Opal.

**Describe alternatives you've considered**
N/A

**Additional context**

Here is an email from a user. This is maybe not the best example as the date format from SPSS was quite strange. But they got very cross about it. I have had other examples with integers getting converted to factors  etc.

> I uploaded a new version of the datafile with dates as yyyy/mm/dd
> 
> "Then I went to the project folder, deleted the previous version of the table, and imported the new one
>   
> ![image](https://user-images.githubusercontent.com/8521654/59673351-0a579500-91b9-11e9-9d54-68c77e572296.png)
> 
> Then I got a new error message
>  
> ![image](https://user-images.githubusercontent.com/8521654/59673360-0fb4df80-91b9-11e9-9e33-fd92c79c0d92.png)
> 
> ..... other steps removed.....
> 
> In a nutshell, the system is very sensitive regarding date format. 
> 
> Best,
> 
> XXXXXX
> "

**Comment by tombisho** [comment]
Another example

![IMG_5318](https://user-images.githubusercontent.com/8521654/59675005-46d8c000-91bc-11e9-99fd-3d1e3bff1aab.JPG)

**Comment by ymarcon** [comment]
As you said, when importing through R (SPSS/Stata/SAS), Opal is just reading a tibble that was loaded by [haven](https://www.rdocumentation.org/packages/haven), and has very few control on the way the data file has been read (just a couple of parameters per read_* function). For instance integers that are turned into decimals (doubles in R) is the choice of haven.

To improve the user experience:

* maybe there are some magic attributes in the R columns that Opal can take advantage of in which case we would need some example data files to identify and make use of them (if there are any). We have done this work with ALSPAC and the SPSS (R) importer/exporter.

* it would be nice in the Opal import preview screen to be able to change data types (and variable names) before the import actually happens.

* it's always tricky to parse dates as there are thousands of possibilities. Opal handles the most common ones automatically, with a preference for the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) one. Do you know from which file format and which importer they have used to get a date type with such a weird date format?

**Comment by tombisho** [comment]
Yes, I can see that this feature has always been tied to haven functionality, but it is very important for a lot of users.

Having an example file does help because you can attempt to import it in R on your machine and highlight any problems. I have tried this in  a few cases.

A preview screen where things can be 'fixed' would also be nice.

The data problem above was when they were using a .sav file in the SPSS (R) importer. I agree that dates are a lot of trouble!

**Comment by ymarcon** [comment]
Will make a test dataset in SPSS to explore the different possible errors. Will also try to catch the error message from tidyverse.
