### ISSUE TITLE
Back slash in label causes SPSS export to fail

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3501]
If a variable label contains a backslash in the label, exporting the table give the error;

org.obiba.opal.spi.r.REvaluationRuntimeException: Error while evaluating 'base::source('.variable-attributes.R')' -> Error : '\u' used without hex digits in character string starting "'(en) CH says\u"

or 

2019, 6:26:08 PM | org.obiba.opal.spi.r.REvaluationRuntimeException: Error while evaluating 'base::source('.variable-attributes.R')' -> Error : '\c' is an unrecognized escape in character string starting "'(en) Total BMD (g\c"

**Comment by kazoompa** [comment]
`\u` is a prefix for uni-code characters as the error indicates. As for the `\c`, is another reserved character. You can try to escape the backslashes: `\\u`.
