### ISSUE TITLE
Copy of view as table

### ISSUE THREAD

**Issue by rwissa** [obiba/opal#3510]
**Describe the bug**
in Opal 2.13.4 when we create a copy of a view, the copy is a table with the same metadata and data as the view copied. the problem is in Opal 2.14.2 where when we create a copy of a view, only the metadata is copied and the table is empty (without data).

**To Reproduce**
1. in a project, select a view 
2. Click on 'copy' from the orange "tools bar" that appears after selecting the view
3. in the pop-up, select the destination desired for the table (copy) being created, change the table name and click 'submit'
4. See error after the copy task is complete

**Expected behavior**
this procedure should create a table which is a copy of the view selected including the metadata and the data.

**Desktop (please complete the following information):**
 - OS: 17763.615
 - Browser: Chrome
 - Version 1809

**Comment by ymarcon** [comment]
I cannot reproduce. Please provide the error message mentioned at step 4.

**Comment by rwissa** [comment]
There is no error message perse but the error is that the table created by the copy only contains the data dictionary but is empty (it contains no data i.e. entities = 0) whereas, the view it was copied from contains the data and the metadata. In opal version 2.13.4 when you make a copy of a view, this new table has the metadata and the data too.

**Comment by ymarcon** [comment]
Ok, but as I said I cannot reproduce. What happens when you export the view?

**Comment by ymarcon** [comment]
Please provide more details: whether the view refers to one one or more tables, if these tables are views etc. All tests that I have ran do not show any issue. Try also to export the view (copy and export actions share the most of the same code).

**Comment by rwissa** [comment]
We were surprised it worked on your end so we tried again (and again) but
we found that the error was on our part in our original table. Thank you
for looking into it for us. Should I close the issue now?
