### ISSUE TITLE
Large number of tasks impacts performance

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3513]
The performance of Opal degrades over time. One possible cause is that tasks are held in memory. 

If a large number of tasks (200) are kept then these will hog memory. One solution is to clear the task list periodically. However if this is a big cause of performance loss, then it would be preferable to store the task list in a file/datastore

**Comment by ymarcon** [comment]
Todo: verify the impact of the tasks list and either fix a leak (not cloased datasource?) and/or evaluate the possibility to store the tasks in OrientDB (and page them).

**Comment by ymarcon** [comment]
According to @sam-story:

> I have discovered a few things:
> 1) Clearing the task list through the UI does not seem to make a difference to the task time. The tasks definitely slow down if you run the same one repeatedly but I'm not sure it's caused by a large task list being held in memory.
> 2) Our training environment which has significantly lower RAM than our Live environment has been importing files faster. One main difference between the servers is the number of project on the Live server is 80 but only 20 on the Training Server. I created another 60 projects on the Training server but this don't seem to impact performance. However after I created more identifier mappings on the Training Server the performance decreased (the Live server already had lots of identifier mappings, around 150). I didn't have time to bench mark this properly or test it consistently but creating 20 mappings and generating identifiers for the 16,000 participants increased the export time of the files by around 25%. We use MySQL for our identifier backend.
