### ISSUE TITLE
Opal 2.14 import into R of numeric values with missing factor

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3515]
I have just upgraded one of our servers to Opal 2.14. The performance is excellent, but I have run into a bit of trouble with some variables where we have defined missing to be -1. That is, the variable might be a decimal, but in the dictionary we define -1 to be missing. We did this in a lot of cases to be explicit with our harmonisation code that we meant something to be missing rather than it being missing by accident.

Now it seems when these are imported into R, they are treated as factors, and the -1s are imported. I think previously the -1s were imported as missing.

Reported by @tombisho

**Comment by ymarcon** [comment]
Test dataset (opal archive format)
[mytest.zip](https://github.com/obiba/opal/files/3422799/mytest.zip)

**Comment by ymarcon** [comment]
The tibble is correct, it's the conversion to plain data.frame that considers every `haven_labelled` class as a factor.

**Comment by tombisho** [comment]
Hi Yannick, I just upgraded to 2.14.3. Now it seems like there is still something a little strange with the object that is available in R:

`> opals <- datashield.login(logins=logindata_all, assign=TRUE)

Logging into the collaborating servers

  No variables have been specified. 
  All the variables in the opal table 
  (the whole dataset) will be assigned to R!

Assigning data:
opal-dev...

Variables assigned:
opal-dev--NUTS_SEEDS, SOY, PBCL, ISOFLAVONES, COV_SUG_BEVS, REGION_CH, BMI_CAT, CONSUMER, COV_DAIRY, COV_FISH, TOTAL, EDUCATION, SMOKING, PA, ALCOHOL, E_INTAKE, COV_FRUIT, COV_VEG, COV_FIBER, AGE_BASE, SEX, TYPE_DIAB, PREV_DIAB, CASE_OBJ_SELF, FAM_DIAB, WAIST, CASE_OBJ, COMORBIDITY, COV_MEAT, FUP_OBJ, FUP_OBJ_SELF, BMI
> ds.summary('D$TOTAL')
The input data is not of the same class in all studies!
Use the function 'ds.class' to verify the class of the input object in each study.
Error:  End of process!
> ds.class('D$TOTAL')
$`opal-dev`
[1] "haven_labelled_spss" "haven_labelled"`

Or have I missed something else I need to do?

Thanks

Tom

**Comment by ymarcon** [comment]
Ok, R class needs to be explicit in a data.frame. Will change that.

**Comment by tombisho** [comment]
Great - thank you
