### ISSUE TITLE
Opal 2.14.2 unable to log in with certificate

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3519]
For some servers we log in with a certificate pair. This seems to have stopped working with Opal 2.14.2, but may have not worked with previous versions (e.g. 2.13) as we have not used these servers for a while.

Error:
```
> opals <- datashield.login(logins=logindata_all, opts = list(ssl.verifypeer=0,ssl.verifyhost=0), directory = '/home/shared/certificates/pa')

Logging into the collaborating servers
*   Trying 172.27.223.186...
* Connected to opal-dev.mrc-epid.cam.ac.uk (172.27.223.186) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
* Closing connection 0
Warning: opal-dev will be excluded: Error in function (type, msg, asError = TRUE)  : 
  error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
```
I am struggling a little to understand the error, but assume that the certificate is rejected on the server side? Is it because they are self-signed?

**Comment by ymarcon** [comment]
Can you try to set the property `org.obiba.opal.security.ssl.allowInvalidCertificates` to true? See http://opaldoc.obiba.org/en/latest/admin/configuration.html

**Comment by tombisho** [comment]
Thanks Yannick. I have done that, the config file is attached just in case I have not added the property correctly.

When I did the upgrade recently, I got asked if I wanted to overwrite the config file and I said no because I did not want to lose the settings. Should I have accepted the new file that came with the distribution?

[opal-config.zip](https://github.com/obiba/opal/files/3446957/opal-config.zip)

**Comment by ymarcon** [comment]
Looks good, does it work?

**Comment by tombisho** [comment]
Sorry, I didn't actually write in the original message that it didn't work, with the same error as before

**Comment by ymarcon** [comment]
The opal server does not trust self signed client certificate by default. The setting "allowInvalidCertificates" is used to change this behavior now (not recommended though).

**Comment by tombisho** [comment]
Just to check my understanding... does this mean if we want to use certificates to authenticate users via DataSHIELD, then this setting is required? I ask this because I am not quite sure how I might generate a CA signed certificate to use for log in purposes. I though the whole point of the CA signed certificates is to prove domain ownership. I'm not quite sure how that would work in the Opal context.

What other implications does the setting have for Opal?

Thanks

Tom

**Comment by ymarcon** [comment]
This setting applies also when connecting to databases (mysql or mongodb) using ssl (whe using self-signed *server* certificates). Client certificate are not linked to a domain, but maybe it is overkill to have them CA trusted, as it is the opal keystore that is the trust manager. I am going to simplify that and accept all client certificates.

**Comment by tombisho** [comment]
Ok got it. Thanks!

**Comment by ymarcon** [comment]
Opal 2.14.4 has been released
