### ISSUE TITLE
Opal server setting

### ISSUE THREAD

**Issue by AlexCosa-Linan** [obiba/opal#3532]
Dear all, 
I am new on OPAL. I hope you can help me with this very basic issue I am having. I have proceed with the installation of OPAL in a server behind my instutution proxy. I can  to log in. However, I can not complete the Post-Install Configuration because the connection to the MYSQL database fails (SQLSchema: Tabular SQL and URL: jdbc:mysql://localhost:3306/opal_ids).
Thanks very much for your help.

I have follow exactly the following steps:

**OPAL Installation and Configuration**

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80  --keyserver-options http-proxy=http://xx.xx.xx.xx:pppp  --recv-keys 379CE192D401AB61

echo 'deb https://dl.bintray.com/obiba/deb all main' | sudo tee /etc/apt/sources.list.d/obiba.list
sudo apt-get update
apt-get install opal

export OPAL_HOME=/usr/share/opal
sudo chmod +x /usr/share/opal/bin/opal
sudo service opal restart

sudo apt-get install opal-rserver
sudo service rserver restart

**MYSQL Installation and Configuration**

sudo apt-get install mysql-server
sudo mysql_secure_installation
sudo ufw allow mysql

sudo nano /etc/mysql/my.cnf
         bind-address = 0.0.0.0

sudo mysql -u root -p
         CREATE DATABASE opal_ids;
         CREATE DATABASE opal_data;
         CREATE USER 'administrator'@'localhost' IDENTIFIED BY 'password';
         CREATE USER 'administrator'@'%' IDENTIFIED BY 'password';
         GRANT ALL ON *.* TO 'administrator'@'localhost';
         GRANT ALL ON *.* TO 'administrator'@'%';
         FLUSH PRIVILEGES;

sudo service mysql stop
sudo service mysql start

**Comment by hjvdwijk** [comment]
The new MySQL authentication with sha2 that does not seem to work with jdbc. Using of the option ‘WITH mysql_native_password’ solved this issue for me

CREATE DATABASE opal_ids;
CREATE DATABASE opal_data;

CREATE USER 'opal'@'localhost' IDENTIFIED WITH mysql_native_password BY '<opal-user-password>';
GRANT ALL ON opal_ids.* TO 'opal'@'localhost' IDENTIFIED BY '<opal-user-password>';
GRANT ALL ON opal_data.* TO 'opal'@'localhost' IDENTIFIED BY '<opal-user-password>';
FLUSH PRIVILEGES;

**Comment by AlexCosa-Linan** [comment]
Thanks for your reply @hjvdwijk. Unfortunately it didnot solve my problem.

**Comment by ymarcon** [comment]
When you connect to the mysql database with the 'opal' user using the mysql client, are you able to verify the access to the opal_ids and opal_data databases?

**Comment by AlexCosa-Linan** [comment]
@ymarcon Yes, I am.

**Comment by hjvdwijk** [comment]
Might be a number of things. First thing to check would be if MySQL allows remote connections, e.g. by using regular client to make the connection (bind-address configured, firewalls port opened, etc.) If this works than you could try a small java application to test the connection e.g. https://www.javatpoint.com/example-to-connect-to-the-mysql-database, that helped my with a better error message to point to the cause.

**Comment by AlexCosa-Linan** [comment]
Thanks for your suggestion. My problem was that no timezone propertie is defined in MySQL. It has been fixed using URL: jdbc:mysql://localhost:3306/opal_ids?**serverTimezone=UTC**. Thanks for your time on this basic issue.
