### ISSUE TITLE
Opal 2.15 behaviour changed for data import from Opal to R

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3533]
With Opal 2.15 we are seeing an issue with the data import from Opal to R.

One data set has a variable which is an integer in Opal with categories defined is imported as an integer into R, rather than a factor. A similar data set correctly imports as a factor, so I am confused as to why this happens.

With the problematic data set, we get the following warning at log in, and I don't know if this is related:

```
Assigning data:
opal-dev...
Warning: Data assignment of 'DIETARY_PATTERNS.ARIC_pattern_harm' failed for 'opal-dev': org.obiba.opal.spi.r.REvaluationRuntimeException: Error while evaluating 'base::source('.variable-attributes.R')' -> Error in base::source(".variable-attributes.R") : 
 attempt to use zero-length variable name

Variables assigned:
opal-dev--.id, SOY, REGION_CH, HYPERTENSION, 
```
I notice in the list of variables that there is a mysterious .id variable, which does not exist in the Opal data set.

**Comment by ymarcon** [comment]
Can you provide a reproducible example on opal demo https://opal-demo.obiba.org (credentials: administrator/password)?

**Comment by tombisho** [comment]
Let me try...

**Comment by tombisho** [comment]
I think I may have got to the bottom of it. While I was trying to set up a dataset to reproduce, I saw that one of the variables had a category with no name. By removing this problem category, I think it has fixed it for us, and I am just waiting for our user to confirm he is happy again.

Opal won't let you do this explicitly, but if you create a category with a name, save it, then delete the name you can save it, then you get problems... although I get a different error to the one I saw on our server.

See Tom.LifeLines on https://opal-demo.obiba.org , variable SMK31

**Comment by tombisho** [comment]
Here is the error:

```
Assigning data:
opal-dev...
Warning: Data assignment of 'Tom.LifeLines' failed for 'opal-dev': org.obiba.magma.MagmaRuntimeException: Not a decimal value: 

Variables assigned:
opal-dev--.id, GESLACHT, GEWICHT, LENGTE, HEALTH17A1, HEALTH17B1, HEALTH17D1, DBPa, SMK11
```
And it does have the same effect of breaking categories for all variables

**Comment by ymarcon** [comment]
Sure, a category without name must never happen, makes no sense! I am going to strengthen the code.

**Comment by tombisho** [comment]
Sounds good, thanks.

Hopefully our user will be happy that this was really the root cause...

**Comment by tombisho** [comment]
User reports that things seem to be working OK now
