### ISSUE TITLE
No results when searching with long variable names

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3534]
The search in both Opal and Mica does not return results when more than 20 chars are entered.

In Opal do a search for "DISORDER_OCCURRENCE"
https://opal-demo.obiba.org/ui/index.html#!search/!variables;rq=contains(DISORDER_OCCURRENCE)
8 results are returned including the variable  STOMACH_DISORDER_OCCURRENCE.COMMENT

Now do a search for "DISORDER_OCCURRENCE.C"
https://opal-demo.obiba.org/ui/index.html#!search/!variables;rq=contains(DISORDER_OCCURRENCE.C)
No variables are returned, even though 4 of the results from the previous search match this pattern.

The same issue occurs in Mica

https://www.maelstrom-research.org/mica/repository#/search?query=variable(match(DISORDER_OCCURRENCE,Mica_variable.name))&type=variables&display=list
The above returns 8 variables

https://www.maelstrom-research.org/mica/repository#/search?query=variable(match(DISORDER_OCCURRENCE.C,Mica_variable.name))&type=variables&display=list
The above returns 0 variables.

**Comment by ymarcon** [comment]
Could it be due to the "." in the name instead?

**Comment by sam-story** [comment]
Searching for STOMACH_DISORDER_OCCURRENCE doesn't return any results either and I'd expect 2
https://opal-demo.obiba.org/ui/index.html#!search/!variables;rq=contains(STOMACH_DISORDER_OCCURRENCE);o=0;s=_score%253Adesc

**Comment by ymarcon** [comment]
The 20 char limit is coming from the ES default setting:
https://github.com/obiba/opal-search-es/blob/master/src/main/conf/elasticsearch.yml#L24

You can change this setting in your ES setup (the ES plugin setting is located at ``OPAL_HOME/plugins/opal-search-es-1.0.0/elasticsearch.yml``), remove the variables index (Administration > Search > Variables Index), wait for the data dictionaries to be automatically re-indexed and try again your search.

**Comment by kazoompa** [comment]
Hi Sam,

Just a note of warning, making the max value of an nGram filter has an
impact on the size of the ES index sizes. I found the article below
interesting. In the future, we could also implement a fallback strategy
when the length of a search filter is very long:

https://medium.com/@ashishstiwari/what-should-be-the-value-of-max-gram-and-min-gram-in-elasticsearch-f091404c9a14

Ramin

**Comment by sam-story** [comment]
Thanks Ramin,
I have increased "max_gram" to 40, and this seams to have increased the disk space used by elasticsearch from 25G to 45G.
This is an acceptable increase for us but we'll need to monitor it. If there is an alternative fallback strategy you could implement in the future it expect that would be useful as 20 is quite low for a variable naming convention.

**Comment by ymarcon** [comment]
Please open a disctinct issue for the fallback feature (which may be not what the final user expects as the behavior will change when beyond the max nGram value).
