### ISSUE TITLE
Opal Views button not working in Edge

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3535]
when using Microsoft Edge the Opal Views button on the Cart page does not do anything when clicked.

An invalid argument error is thrown in the console.
![image](https://user-images.githubusercontent.com/34068523/64545701-1e76e280-d321-11e9-9ea4-bb05f8777f62.png)

**Comment by ymarcon** [comment]
This is a Mica issue. Could you log this in mica's repo instead?
