### ISSUE TITLE
Minor - 'missing' category displayed in DataSHIELD for categorical variables

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3541]
**Describe the bug**
When defining a missing category on a categorical variable (for example -1 is missing), this category is carried through to DataSHIELD but with 0 entries. This causes concern that missings are not being handled correctly (they are).

**To Reproduce**

```
server <- c('demo')
url <- c('https://opal-demo.obiba.org')
table <- c('tom.mytest')
password <- c( 'password')
user <- c( 'administrator')
logindata_all <- data.frame(server,url,user,password, table)

datashield.logout(opals)

opals <- datashield.login(logins=logindata_all, assign=TRUE)

ds.summary('D$illness')
```

**Expected behavior**
The missing category is not displayed in the summary

**Desktop (please complete the following information):**
v2.15.1

**Comment by ymarcon** [comment]
This behavior was designed on purpose since the very beginning of DS (thus this is not a bug) so that the calculations happen correctly by default (average calculation for instance). Nevertheless the possibility to assign missing values is an option of the datashield.assign() function.

**Comment by tombisho** [comment]
Hmm... something has definitely changed though in recent versions. I have one cohort on 2.13.2. It has a variable SMOKING_1, with categories 0,1,-1, with -1 set as missing. If I connect and do a summary I get:

```
> ds.summary('D$SMOKING_1')
$demo
$demo$class
[1] "factor"

$demo$length
[1] 84968

$demo$categories
[1] "1" "0"

$demo$`count of '1'`
[1] 20139

$demo$`count of '0'`
[1] 63299

```
So the '-1' category is not listed.

Whereas in the example I uploaded to the obiba demo server (2.15.1), we have the same category structure, but the -1 is listed with 0 entries:

```
> ds.summary('D$illness')
$demo
$demo$class
[1] "factor"

$demo$length
[1] 63

$demo$categories
[1] "-1" "0"  "1" 

$demo$`count of '-1'`
[1] 0

$demo$`count of '0'`
[1] 28

$demo$`count of '1'`
[1] 21

```
So the behaviour seems to me to have changed recently. And it is this listing of the -1 category that is concerning one of our researchers.

I agree that it does not impact the analysis, because when -1 is marked as missing in Opal, it has 0 entries in DataSHIELD.

**Comment by ymarcon** [comment]
Ah ok, I was talking about the data, not the meta-data. Even if the missing categories are listed in the vector's attributes (that are inspected by levels() to build the $categories), all the corresponding values have been replaced by NAs. I can fix that.

**Comment by tombisho** [comment]
OK great, thanks for fixing it. As you say, from an analysis point of view there is no problem as missing values are correctly replaced by NAs. It was just confusing one of our researchers to see the -1 category there.
