### ISSUE TITLE
OPAL Installation Issue (Do not open Opal on web)

### ISSUE THREAD

**Issue by carlosmontenegrodeveloper1** [obiba/opal#3549]
Hello dear Opal's team.
Carlos From Nicaragua.

I have installed OPAL (On Debian 10-buster and later on Ubuntu 18) using Debian package installation instructions: https://www.obiba.org/pages/pkg/

So, I installed completely all, OPAL, MICA and AGATE. Then in the console, I verified Opal service with:  Sudo service Opal status and it is active, but when I go to the browser using http://localhost:8080 or http://localhost:8443, I can not see Opal on web.

Now, reading the log, I have found an issue related to a class. It is: 

Caused by: java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
Caused by: java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
Caused by: org.springframework.beans.BeanInstantiationException: Failed to ins$
Caused by: org.springframework.beans.BeanInstantiationException: Failed to ins$
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java$
        at org.springframework.beans.factory.support.SimpleInstantiationStrate$
        at org.springframework.beans.factory.support.AbstractAutowireCapableBe$
        ... 17 common frames omitted

![issue1](https://user-images.githubusercontent.com/57047653/70815782-c45c4200-1d93-11ea-9f5c-58693b8724d7.png)
![issue2](https://user-images.githubusercontent.com/57047653/70815783-c45c4200-1d93-11ea-9c6f-ec5634eae4bb.png)
![issue3](https://user-images.githubusercontent.com/57047653/70815784-c4f4d880-1d93-11ea-9712-1ef745742ef0.png)
![issue4](https://user-images.githubusercontent.com/57047653/70815785-c4f4d880-1d93-11ea-8f69-e6b26186604f.png)
![issue5](https://user-images.githubusercontent.com/57047653/70815786-c4f4d880-1d93-11ea-93aa-69e59294c7a0.png)

![opal service on](https://user-images.githubusercontent.com/57047653/70815977-287f0600-1d94-11ea-9d01-2e1c313a17a1.png)

Thank you in advance,
Carlos
...

**Comment by ymarcon** [comment]
Java 8 is required. Default Java version on ubuntu 18 is 11.

**Comment by carlosmontenegrodeveloper1** [comment]
Hello Marcon.
Thanks for your answer.

Friend, I am trying both, ubuntu and debian. So, I still have the issue after installation of OpenJDK8.
Do I need to install Oracle-jdk8, Java8 or OpenJDK-8 ?

Thank you,
Carlos

**Comment by ymarcon** [comment]
Install openjdk-8-jre (oracle distribution is useless) and verify with `java -version`. If it is still java 11 that is set as the default java, you can use this command `update-alternatives --config java` OR you can specify which java is to be used in the `/etc/default/opal` file (`JAVA` environment variable).

**Comment by carlosmontenegrodeveloper1** [comment]
Hello dear Mr.Marcon
Good Morning.

I have downloaded Oracle jre1.8.0_231.tar.gz and descompressed. Then in /etc/default I modified the java location    #> /usr/bin/java8/jre1.8.0   and got it! 

So, I attach the image, but using user:administrator/password:password, I could not enter to the app.
Now, my question is about next step. I mean, 
1. How to use Opal?  user and password.
2. How to install databases?
3. Do I have to create a new thread for these questions?

Thank you so much for helping me.
Carlos
...

![Opal home](https://user-images.githubusercontent.com/57047653/70872698-99c6e080-1f6f-11ea-84b2-af3f67175b64.png)

**Comment by ymarcon** [comment]
If you have installed the debian package, you were asked for the administrator's password. If you have forgotten it, you can update the administrator's password in the /etc/opal/shiro.ini file (to be hashed using the `shiro-hasher` tool), see documentation:
http://opaldoc.obiba.org/en/latest/admin/configuration.html#user-directories

For the database setup, see documentation:
http://opaldoc.obiba.org/en/latest/web-user-guide/administration/databases.html

**Comment by carlosmontenegrodeveloper1** [comment]
Good Morning Mr.Macon.
Thank you so much for helping.

Suddenly, the previous configuration was not recognized (It was using Oracle jre8 from a package).
Then put openJDK8 as default. It works.

I am very new in all of this. Sorry.
Now, I am trying to enter to Opal. So, I am configuring shiro.ini, but I have no result. This is my main file:

# =======================
# Shiro INI configuration
# =======================

[main]
#---
myRealm = com.company.shiro.realm.MyRealm;
myRealm.connectionTimeout = 30000;
myRealm.username = cmontenegro;

sha256Matcher = org.apache.shiro.authc.credential.Sha256CredentialsMatcher
myRealm.credentialsMatcher = $sha256Matcher
securityManager.rememberMeManager.cipherKey = kPH+bIxk5D2deZiIxcaaaA==

[users]
administrator=$shiro1$SHA-256$500000$GqrdF1zwv9UE+d9wPA5+hg==$dGEtAsiVVQWWx5ab$
cmontenegro= Abc.123,admin

[roles]
admin = *
# =======================

After, I tried with this:

# =======================
# Shiro INI configuration
# =======================

[main]
#---
myRealm = com.company.shiro.realm.MyRealm;
myRealm.connectionTimeout = 30000;
myRealm.username = cmontenegro;

securityManager.rememberMeManager.cipherKey = kPH+bIxk5D2deZiIxcaaaA==

[users]
administrator=$shiro1$SHA-256$500000$GqrdF1zwv9UE+d9wPA5+hg==$dGEtAsiVVQWWx5ab$
cmontenegro= Abc.123,admin

[roles]
admin = *
# =======================

So, I did that, but still any result. What can I do?   
Thank you again,
Carlos
...

**Comment by carlosmontenegrodeveloper1** [comment]
![auth error](https://user-images.githubusercontent.com/57047653/70929451-c6730a80-1ff8-11ea-9f96-fb688b1c92e5.png)

**Comment by kazoompa** [comment]
Hi Carlos,

To create Opal users I suggest you use the `Administration / Users and Groups` module. The INI is mostly used for administrator users.

In any case, you error is that the password is not hashed:

```
./shiro-hasher -p 
```

And type your password `Abc.123`. However, I will suggest you create your Opal users from the admin module as mentioned above.

Best,

**Comment by carlosmontenegrodeveloper1** [comment]
Hello Kazoompa (is your name?)

Friend, thank you for writing.
My problem is that I am in the login screen, but I can not enter for using admin module.

So, I am trying to create a new user and then log in, but I have found issues like that 
in shiro.ini.

I have not installed databases yet, justI installed Opal using debian package  ( https://www.obiba.org/pages/pkg/  ), and finally I could see the login screen.

If you mentioned that I must use admin module, what did I do bad during the installation?

Thank you in advance,
Carlos

**Comment by kazoompa** [comment]
Hi Carlos,

Your `administrator` password setting in the `shiro.ini` is missing the role `admin`. 

Here are the steps once more:
```bash
cd /usr/share/opal/tools
./shiro-hasher -p # enter your a password word for your administrator
cd /etc/opal
vi shiro.ini # add the password and the role (,admin)
```
Make sure the `shiro.ini` has the correct ownership, i.e., `opal:adm`:
```
ls -al /etc/opal
``` 

Here is an example of a correct setting:
```
administrator=$shiro1$SHA-256$500000$E8xJq5fufDeEYoERQmQcUQ==$h5Y8Jy3SExyhLPqi9avMtt2Cj74GxsZGjZOn++ELCs4=,admin
zipizape=$shiro1$SHA-256$500000$7wF8JFDfqAJxTJbL/vO2pg==$ovWk5qFdAi8dzg3gSS/jSwcjxCAKuOxFLfDhvltVh6A=,admin
```

BTW, my name is Ramin :)

Best,

**Comment by carlosmontenegrodeveloper1** [comment]
Hello Ramin !
Thank you friend.

I did what you recommended. So, this is my shiro.ini:

# Shiro INI configuration

[main]
myRealm = com.company.shiro.realm.MyRealm;
myRealm.connectionTimeout = 30000;
myRealm.username = cmontenegro;

securityManager.rememberMeManager.cipherKey = kPH+bIxk5D2deZiIxcaaaA==

[users]
cmontenegro= $shiro1$SHA-256$500000$cPo9qGdlS4CUtTitbdf8pg==$FYgJlY0Sw54XpBLRF$XpBLRF3Dz5YbehznJiXBYmjd7M3MNWQc=,admin

[roles]
admin = *

#--

So, that is the generated code and shiro.ini is correct.  opal:admin.
Later, I try to login with  user: cmontenegro, password:  abc.123, but I can not enter to the app yet. 

What can I do?
Thank you in advance,
Carlos
...

**Comment by kazoompa** [comment]
Can you remove your realms settings and try again? Can't you use the
default realm setting?

BTW, you can always download the server logs in `Administration /Java
Virtual Machine`, you may see some useful error messages.

Ramin

**Comment by carlosmontenegrodeveloper1** [comment]
Hello Ramin,

I removed now, and just using the blocks 'Roles' and 'users'. The same issue.

So, I could read the log:

$refused); nested exception is org.apache.http.conn.HttpHostConnectException: $Connection failure with identification server: [I/O error on POST$POST request for "https://localhost:8444/ws/tickets": Connect to localhost lhost:8444 [localhost/127.0.0.1] failed: Conexión rehusada (Connection refuse nested exception is org.apache.http.conn.HttpHostConnectException:
2019-12-16 15:32:12,515 [qtp850300711-137] WARN  org.obiba.shiro.web.filter.Ab$
2019-12-16 15:32:12,515 [qtp850300711-137] INFO  org.obiba.opal.web.security.A$

On the other hand, I have a coworker in Colombia who did not have any issue.
What is the best way for installing friend? Documentation says to download the package .deb.
I did that reading:  https://www.obiba.org/pages/pkg/.

Thanks,
Carlos
...

**Comment by kazoompa** [comment]
If you don't have any data try to reinstall Opal following the [install](https://www.obiba.org/pages/pkg/) instructions. Do not touch the `shiro.ini` as creating Opal users is much easier from the Admin section. As Yannick mentioned, when you install Opal via a Debian package you get prompted for the password.

Ramin

**Comment by carlosmontenegrodeveloper1** [comment]
Good Morning dear friend Ramin.
Thank you so much.    

As you mentioned, the admin's password during the installation. 
I am configuring databases now. 

1. In Identifiers data base:
  1.1 What is the difference between Tabular SQL and Opal SQL?

2. In Data Database:
  2.1 Do I need to check the option: Project Default storage?

Best,
Carlos
...

**Comment by kazoompa** [comment]
Hi Carlos,

If this bug is resolved please open a new issue or user [OBiBa Users](https://groups.google.com/forum/#!forum/obiba-users) group.

1.1. https://groups.google.com/forum/#!forum/obiba-users
2.1. Yes, if you want that database be the Default Storage for all projects

Best,

**Comment by carlosmontenegrodeveloper1** [comment]
Hello dear Ramin.
Hope you are in good health.

Yes, I understand.
The bug is resolved, just a question: What is the difference between Tabular SQL and Opal SQL?

Thank you friend,
Carlos
...

**Comment by carlosmontenegrodeveloper1** [comment]
Thank you so much.
I found the answer.

Best,
Carlos
