### ISSUE TITLE
Uploading table (MS-Excel file .xls) issue

### ISSUE THREAD

**Issue by carlosmontenegrodeveloper1** [obiba/opal#3550]
Hello dear team.

**Describe the bug**
I try to upload a table from a MS-Excel file with format 97-2003 (.xls) and the system
is working indefinitely. So, it happens in a second project, adding a new tables.

Note: I could upload files in my first project.

**To Reproduce**
1. Go to Projects and select yours.
2. Click on 'Add table'
3. Select 'Add/Update tables from dictionary...'
4. Click on 'Browse button'
5. Select your file
6. Label local: sp
7. Character set: UTF-8
8. Click on 'Next button'
9. See error (System working indefinitely)

**Expected behavior**
To see the content of the file (DataSource)

**Screenshots**
Attached an image of the issue

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version [71.0 64 bits]

 - Browser: Chrome
 - Version [79.0.3945.79 (build official) (64 bits)]

-------

Thank you in advance,
Carlos

![upload table issue](https://user-images.githubusercontent.com/57047653/71196438-b4da6e80-2255-11ea-93d9-bad4b833d70e.png)

**Comment by carlosmontenegrodeveloper1** [comment]
Note: The Log file does not content any message related to this case.

**Comment by ymarcon** [comment]
Could you attach the Excel file to this issue?

**Comment by carlosmontenegrodeveloper1** [comment]
Hello Mr.Marcon.

Yes, I am attaching the file.
Thanks,
Carlos

[co_comments_arbovirus.zip](https://github.com/obiba/opal/files/3985018/co_comments_arbovirus.zip)

**Comment by ymarcon** [comment]
If you look at the [Excel template](https://github.com/obiba/opal/raw/master/opal-server/src/main/resources/META-INF/templates/opalVariableTemplate.xls) that is provided, you will see that 2 worksheets are expected: Variables and Categories. You have none of them in your Excel file. BTW you should consider creating the dictionary directly from the web interface.

**Comment by carlosmontenegrodeveloper1** [comment]
Hello Mr.Marcon,
You are right.

It would be good if the system can generate any message to the user indicating the error and how to solve it.

Thank you,
Carlos
...
