### ISSUE TITLE
Harmonized table as result of Add table process - Issue

### ISSUE THREAD

**Issue by carlosmontenegrodeveloper1** [obiba/opal#3551]
**Describe the bug**
Hello dear Team.

I added a new table to my project (The second one), but in the field 'opal.id' (I think it is the primary key in the harmonized table) has date values and not identity or consecutives numbers (1,2,3) as usual. So, I could see the first table and opal.id has consecutive numbers correctly.

**To Reproduce**

1.    Go to Projects and select yours.
2.   Click on 'Add table'
3.   Select 'Add/Update tables from dictionary...'
4.   Click on 'Browse button'
5.    Select your file
6.    Label local: sp
7.    Character set: UTF-8
8.    Click on 'Next button'
9.    Click on 'Finish button' (You can see the new table in 'Table Screen')
9.    Go to Mysql database and make a (select * from harmonized_table) and then will see error:
       The field 'opal.id' (I think it is the primary key in the harmonized table) has date values and not 
        identity or consecutives numbers (1,2,3). So, Those date values do not exists in .cvs file. 

**Expected behavior**
The field opal.id with consecutive numbers generated correctly.

**Screenshots**
I am attaching a zip file. (files in .csv and .xls format and an image from mysql database).

**Desktop (please complete the following information):**
    OS: Ubuntu 18.04
    Browser: Firefox
    Version [71.0 64 bits]

    Browser: Chrome
    Version [79.0.3945.79 (build official) (64 bits)]

---

Thank you in advance,
Carlos

[dm_demographic_hospitalario.zip](https://github.com/obiba/opal/files/3985382/dm_demographic_hospitalario.zip)

**Comment by carlosmontenegrodeveloper1** [comment]
Image...

![opal_id as date](https://user-images.githubusercontent.com/57047653/71206355-fa089b80-2269-11ea-82cf-e3c7ebd14d25.png)

**Comment by ymarcon** [comment]
where does this csv come from?

**Comment by carlosmontenegrodeveloper1** [comment]
It has been generated using OpenOffice

**Comment by ymarcon** [comment]
ok, but I mean this is the data file that you have imported and there is no identifier column in it. Opal requires the IDs to be provided and it assumed that the first column was the identifiers column (this behavior might change depending on the importer). This is required because Opal supports multiple lines per participant and this handled by inspecting the ID column. Any way, you have in your SQL table what you have provided.

**Comment by carlosmontenegrodeveloper1** [comment]
Good Morning Mr.Marcon,
Thank you for writing. I will analize what you have commented about the importer.

Greetings,
Carlos
...
