### ISSUE TITLE
Generated view empty - Issue

### ISSUE THREAD

**Issue by carlosmontenegrodeveloper1** [obiba/opal#3552]
**Describe the bug**
Hello dear team.

I have created a new view, but when check the values, it is empty.

**To Reproduce**
1. Select your project
2. Click on 'Add table'
3. Select  'Add view'
4. Introduce name, select table reference and choose variable file (.xls file)
5. Click on 'Save button'
6. Select your new view
7. Go to 'Value tab' in view's details
4. See error, view is empty.

**Expected behavior**
View with information

**Screenshots**
I am attaching a zip file. (files in .csv and .xls format and an image of the view).

**Desktop (please complete the following information):**
OS: Ubuntu 18.04
Browser: Firefox
Version [71.0 64 bits]

Browser: Chrome
Version [79.0.3945.79 (build official) (64 bits)]

....
Thank you in advance,
Carlos

[view issue.zip](https://github.com/obiba/opal/files/3985459/view.issue.zip)
![view issue](https://user-images.githubusercontent.com/57047653/71206308-dcd3cd00-2269-11ea-84a9-163b9522b852.png)

**Comment by ymarcon** [comment]
If you do not define derivation scripts, you cannot expect Opal to guess what are the values of the view.

**Comment by carlosmontenegrodeveloper1** [comment]
Mr.Marcon,
Thank you for your help,
Carlos
