### ISSUE TITLE
Files "Last updated" when logged into opal web portal always incorrect

### ISSUE THREAD

**Issue by alexwesterberg** [obiba/opal#3561]
Even if I've just uploaded a new file to the opal web portal for datashield virtual machine, it claims the file is 18 hours old/ 2 weeks old/ etc. Not 5 minutes old which is what it should say. Shutting off the VM and turning it on again, logging in again to the web portal, confuses it even further- the "last updated" numer can have changed radically from when you were logged in the previous time. What could be causing the erratic behaviour?

**To Reproduce**
- Create a new .csv or .xls file, can be blank
- Launch a datashield VM, log onto opal web portal
- In files, upload the new spreadsheet
- In projects, add that new file to a new project

**Expected behavior**
- View the "last updated" for that file, if it's anything like my experience it will be incorrect.

**Desktop**
 - OS: Ubuntu 18.04
 - Browser: Firefox 74.0 (64-bit)
 - Version: ?

**Comment by ymarcon** [comment]
I cannot reproduce this behavior neither with a plain install, nor with a docker install (see opal-demo.obiba.org for instance). The last modification date of the files is an information that comes directly from the host's file system. Probably the VM itself is the issue.
