### ISSUE TITLE
Method to export project with views preserved as views rather than calculated tables

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3563]
I have an Opal instance with many projects. Each projects has raw data in tables and harmonised data in views. I wish to be able to export all projects and reimport them into Opal on Coral. At the moment the export functionality archives the harmonised views as tables with the values calculated. The harmonisation algorithms are lost. These are vital for understanding how the data are derived.

I would like a way to export views as views to preserve the harmonisation, mainly through the command line but it could be useful on the UI too. On the command line, I'm sure if it is possible just to export all tables in a project without listing them. It would be nice not to have to list them, just export everything in the project.

**Comment by ymarcon** [comment]
I will implement this as a project data backup/restore feature. The backup archive will contain:
* exported tables
* views as logical tables (backup/restore of a single view is already implemented)
* resources
* files

On restore from the projects list page, selecting such project data backup archive will reinstate its content, after selecting the associated database and providing a project name.

On restore from an existing project, the data will be imported (override/merge option).

**Comment by tombisho** [comment]
Great! Thank you
