### ISSUE TITLE
Docker image for the latest version

### ISSUE THREAD

**Issue by tanjascats** [obiba/opal#3575]
It seems like "obiba/opal:latest" is not an image of the latest version of Opal. It would be very useful to have the Docker Image of the latest version for everyone using Opal this way.

**Comment by ymarcon** [comment]
I think it is, as https://opal-demo.obiba.org/ is based on this image. 
It is probably a docker cache issue on your side. Use [docker pull](https://docs.docker.com/engine/reference/commandline/pull/) to fetch the image.

**Comment by tanjascats** [comment]
I pulled the docker image and restarted the container and I believe I am running the latest version at the moment. 

The real issue I'm dealing with (unrelated to Docker image, but I thought the version was the problem) is the unavailability of `opal project` [command](http://opaldoc.obiba.org/en/latest/python-user-guide/project/index.html) which is supposed to be available with the latest version, as far as I understood. The available commands from the Python client are these in the following screenshots.
![image](https://user-images.githubusercontent.com/44204145/85566352-432e1380-b630-11ea-9b61-0b6bef570e63.png)
![image](https://user-images.githubusercontent.com/44204145/85566452-57721080-b630-11ea-8c36-22c74254d578.png)

Do you maybe have a suggestion of where to start with solving this problem? I appreciate the help.

Thank you

**Comment by kazoompa** [comment]
Hi,

If you have installed Opal Python Client, you may want to update it, the
latest version is 3.0.1
<https://github.com/obiba/opal-python-client/releases/tag/3.0.1>.

Best,
