### ISSUE TITLE
uploading dictionaries with missing labels

### ISSUE THREAD

**Issue by joerghenkebuero** [obiba/opal#3582]
I can upload a data dictionary as provided in the template but without a label for a variable. The import works, also creating the opal tables in the opal application works. But as I want to use that dictionary in MICA, loading the variables does not work. Therefore, the label field is mandatory, but the upload process in opal doesn't check that.

**To Reproduce**
Upload a damaged opal template dictionary to opal, create a study in mica and add that opal data dictionary to the study. Try to browse the study variables.

Besides: In Mica, I get this javascript error:
```javascript
TypeError: "summary.variableLabel is undefined"
```

**Expected behavior**
Opal forbids uploading templates that have missing label entries.

**Desktop (please complete the following information):**
 - OS: doesn't matter
 - Browser: doesn't matter, but I used firefox
 - Version: the current one (3.0)

**Comment by ymarcon** [comment]
This is a more a Mica issue as Opal makes no assumption regarding what will be the usage of the data and dictionaries. In addition to that the dictionary could be built step by step so it should not forbid missing labels. 

Could you please open an issue in [Mica](https://github.com/obiba/mica2) for a better handling of the missing variable label?

What I would suggest for Opal is a dictionary validation feature that would check for:
* variable without label(s)
* attributes that are not defined by a taxonomy

**Comment by joerghenkebuero** [comment]
created the new issue in MICA: https://github.com/obiba/mica2/issues/3977
