### ISSUE TITLE
table_save uses incorrect default data type when data is empty and cannot be changed before or later by dictonary_update

### ISSUE THREAD

**Issue by hjvdwijk** [obiba/opal#3587]
**Is your feature request related to a problem? Please describe.**
We upload data from various sources. It may be that some data is not yet filled in and thereby null/na in the data set. When uploading data to Opal, Opal determines the data type and repeatable from the data. Since there is no data for some variables, Opal uses the default type 'text' and repeatable 'no'. This however, is not correct and causes an error when updating the dictionary, e. g. Error: Client error: (400) Bad Request; MagmaRuntimeException: Incompatible value types for variable [myVar]: 'org.obiba.magma.type.DecimalType@5bed1370' / 'org.obiba.magma.type.TextType@36454c'
Opal does not support upload the dictionary first, the data upload will erase the dictionary. So it is not possible to specify the data type in advance.

**Describe the solution you'd like**
It would be better to be able to specify the correct datatype and repeatable. This could be done either before uploading the data (first upload the dictionary and then the data). That would mean that the data upload would have to keep the dictionary. The other option would be to allow upload of a dictionary with modification of the data type for modifications that will not loose any data e.g. change data type when no data for this var, repeatable no -> yes, , etc.

**Describe alternatives you've considered**
I tries to adjust the dictionary from the Opal data. However that causes several issues. The types are not correct in the catalogue. Also having the same variable in multiple tables can have different definitions from this issue and then this data cannot be combined in Opal views, even when this variable is not used in the combined data

**Additional context**

**Comment by ymarcon** [comment]
You are right, Opal delegates to the `readr` R package that reads the first lines of the csv file to guess the types, but if no data are available it fallbacks to a default type.
I'll check if we could have a general approach that automatically converts the imported values into the destination data type (if already defined and different from the source one).

**Comment by ymarcon** [comment]
Update (misunderstanding, forget the reference to readr): 

For each column Opal [determines the data type by using a combination of `class()`, `tibble::type_sum()` and `attributes()`](https://github.com/obiba/opal/blob/master/opal-spi-r/src/main/java/org/obiba/opal/spi/r/datasource/magma/RVariableValueSource.java#L127-L150). If `class` and `type_sum` do not help, it fallbacks to the value of the R attribute `opal.value_type` and then to the default type '`text`'.
Regarding the repeatability, it uses the R attribute `opal.repeatable` if it is defined.

Could you try to decorate your dataset columns with `opal.value_type` (one of text, integer, decimal etc.) and `opal.repeatable` (0 or 1) ?

**Comment by ymarcon** [comment]
Note that using the `opal.value_type` R attribute is a fallback action. Maybe it should come first?

**Comment by hjvdwijk** [comment]
Thank you. This works for value_type, I will check repeatable at a later time

attributes(opal_data$myVar) <- list("opal.value_type"="decimal")

**Comment by hjvdwijk** [comment]
I think you are right. Explicitly specified would be better to have priority over automatically detection.

**Comment by ymarcon** [comment]
Ok, I will make a patch release of Opal then.

**Comment by ymarcon** [comment]
opal 3.0.3 released, `opal.value_type` R attribute gets priority over the column class/type.

To apply the attribute (without scrapping the other attributes):

```
attributes(opal_data$myVar)$opal.value_type <- "decimal"
```

This can be combined with `opal.repeatable`, `opal.occurrence_group`, `opal.unit`, `opal.mime_type`, `opal.index`, `opal.referenced_entity_type`.
