### ISSUE TITLE
timing issue in harmo.table_save

### ISSUE THREAD

**Issue by hjvdwijk** [obiba/opal#3588]
**Describe the bug**
Sometimes harmo.table_save gives the error:
 "[1] "Error: lexical error: invalid char in json text.\n                                       cannotCreateFolderPathAlreadyEx\n                     (right here) ------^\n\n""

This error occurs randomly and executing the same table_save again works fine. This is not a big issue for manual table_save as the save can be run again. However, for unattended scripts, this is an issue.

**To Reproduce**
This is not easy to reproduce as the error occurs randomly

**Comment by ymarcon** [comment]
Could you remove all the temporary folders that were created in the Opal's file system at path "/tmp". There should be remaining folders (named with numbers) that were not cleaned. I will improve this table_save operation (tmp folder name is randomly assigned, but its existence is not checked).

**Comment by ymarcon** [comment]
Please use dev version of opalr:

```
remotes::install_github("obiba/opalr")
```

The function `opal.table_save` (that deprecates `harmo.table_save`) has stronger code for creating a temp folder in the Opal file system (needed in the process of transferring data). In addition to that it reinstates the table permissions when a table is overridden. See also the `opal.table_perm*` functions.
