### ISSUE TITLE
certain variable names in opal leads to false variable names in mica

### ISSUE THREAD

**Issue by joerghenkebuero** [obiba/opal#3589]
**Describe the bug**
Created a variable named `p22_3c` in OPAL by importing an excel file. When this is transferred to MICA, it becomes `p22<`.

**To Reproduce**
1. create a variable name in opal that contains `_3c`.
2. propose that table to MICA and bind the table to a study
3. browse the variables of the study and look for the variable name
4. find `<` instead of `_3c`

**Expected behavior**
The transferred variable names should be taken as is instead of renaming them.

**Screenshots**
OPAL (Version 3.0 from the Debian repository)
<img width="551" alt="grafik" src="https://user-images.githubusercontent.com/69628891/93508772-192e7980-f91f-11ea-8e06-1aebd6acacd7.png">
MICA (Version 4.2.3 from the Debian repository)
<img width="397" alt="grafik" src="https://user-images.githubusercontent.com/69628891/93508836-32372a80-f91f-11ea-9eb9-d9d6b058602e.png">

**Desktop:**
 - OS: Debian Linux Buster
 - Browser: Firefox 68.12.0esr

**Additional context**
`3C` is the hex-coding of `60`, and `60` is the number of the ASCII character `<`. I guess this is not by random...

**Comment by ymarcon** [comment]
Good catch, this is a Mica issue. It will be fixed as soon as possible.

**Comment by ymarcon** [comment]
Fixed in Mica 4.2.4

**Comment by joerghenkebuero** [comment]
thank you very much for that quick bugfix! This has been solved within 3 hours - quite fast!
