### ISSUE TITLE
Changes to the dd download form

### ISSUE THREAD

**Issue by sofiyad** [obiba/opal#3590]
Request from Karla:
Basically, when we download a datadictionary from Opal, the file only contains columns for the domains that were actually used in the study.(So instead of 18 columns for each domain, there are columns for the tags that were used) So this is an issue when we have to correct many of variables, because we have to add the columns that we need for corrections manually. So the solution for this, would be to have the 18 columns(even if some are empty) when we download the dictionaries from opal.

**Comment by kazoompa** [comment]
This should not be by default, possibly on demand (an option). As for the level difficulty, I do not think it is hard, need to look into the code.

**Comment by ymarcon** [comment]
Or do it in R...

**Comment by ymarcon** [comment]
Recipe:

```
library(opalr)
o <- opal.login(username = "administrator", password = "password", url = "https://opal-demo.obiba.org")

# get the dictionary, format is same as the excel one
dico <- opal.table_dictionary_get(o, "CPTP", "Coreqx_final")

# check column names
names(dico$variables)

# add/update a column
dico$variables$`Mlstr_area::Xyz` <- unlist(lapply(dico$variables$name, function(name) {
  if (startsWith(name, "A_SDC_EDU")) {
    "Education"
  } else {
    NA
  }
}))

# remove a column
dico$variables$`Mlstr_area::Abc` <- NULL

# update dico
opal.table_dictionary_update(o, "CPTP", "Coreqx_final", variables = dico$variables, categories = dico$categories)

opal.logout(o)
```

**Comment by sofiyad** [comment]
This was assigned to Guillaume to look into, now on hold indefinitely due to an upcoming change in the tagging template
