### ISSUE TITLE
Opal service Active (Exited)

### ISSUE THREAD

**Issue by carlosmontenegrodeveloper1** [obiba/opal#3592]
Hello dear Obiba team.

I have an issue with Opal service status.
So, I already installed Opal on Debian 10 with Java 8, but when check service status, I have:
   Opal service Active (Exited)

I know it must be as (Running), and when try to open it on a browser, I can not.
What could be the main problem?

Thank you in advance,
Carlos

**Comment by ymarcon** [comment]
Please check what is in the opal.log file.

**Comment by carlosmontenegrodeveloper1** [comment]
[Opal active(exited).pdf](https://github.com/obiba/opal/files/5365848/Opal.active.exited.pdf)
![Opal service status](https://user-images.githubusercontent.com/57047653/95760488-53621100-0c68-11eb-9adf-bd2016f551f9.png)

Hello dear Mr.Marcon.
Good morning.

I attach what have found in the log file.
Thank you in advance,
Carlos
...

**Comment by ymarcon** [comment]
The log file is located at `/var/log/opal/opal.log`.

**Comment by ymarcon** [comment]
Ah ok it is in the pdf. Apparently you are not using java8, most probably because it is not the default java installed. Either change the default one with `sudo update-java-alternatives`, or specify java executable with JAVA setting in [/etc/default/opal](https://github.com/obiba/opal/blob/master/opal-server/src/main/deb/debian/opal.default#L9).

**Comment by carlosmontenegrodeveloper1** [comment]
Hello dear Mr.Marcon.
I am attaching 2 images (java version and java defined in opal default).

Thank you in advance,
Carlos

![Defaul Opal](https://user-images.githubusercontent.com/57047653/95768900-48ad7900-0c74-11eb-9360-d929549c1a0d.png)
![java version jdk8](https://user-images.githubusercontent.com/57047653/95768909-4b0fd300-0c74-11eb-9332-dc973f87cf8a.png)

**Comment by carlosmontenegrodeveloper1** [comment]
but the issue is the same: Opal service Active (Exited)

**Comment by ymarcon** [comment]
Sorry but without the error messages from opal.log file we cannot help.

**Comment by carlosmontenegrodeveloper1** [comment]
Hello dear Mr.Marcon
Good morning.

Yes, the error message from opal.log file is this attached to the message in .pdf format.
I had sent it in previous message.

Thank you in advance,
Carlos
...

[Error Opal.active.exited.pdf](https://github.com/obiba/opal/files/5439622/Error.Opal.active.exited.pdf)

**Comment by ymarcon** [comment]
Then I am sorry to insist, but the error is due to the wrong java version being used. Java 8 is expected/required and I am able to reproduce the error when using java 11 (which is probably your system's default).

**Comment by kazoompa** [comment]
Hi Carlos,

You can also try another tool to manage your Java versions, namely, https://sdkman.io/install.

Basically, you run the following command:

```
curl -s "https://get.sdkman.io" | bash
```
Once you have the sdkman installed, run the following command to list the java versions:

```
sdk list java
```

We recommend  the following version:
```
sdk install java  8.0.262.hs-adpt
```

Best

**Comment by carlosmontenegrodeveloper1** [comment]
Hello Ramin.
Hope you and dear family are doing well.

Thanks for your answer.
Currently I have the Java version: JDK1.8.0_261 as you can see in the image.

So, I have installed with SDKman, but the recommended version is not available (see the image) and get an issue: 
I have Debian 10 booster (64bits). What can I do?

Thank you in advance,
Carlos
...

![java current version 8](https://user-images.githubusercontent.com/57047653/97910979-2efdcf80-1d10-11eb-8013-7733ec71e3f9.png)
![java version issue](https://user-images.githubusercontent.com/57047653/97910981-2f966600-1d10-11eb-906f-8488e0ded49c.png)

**Comment by kazoompa** [comment]
Hi Carlos,

What is the result of sdk list java, that’s the one you should use to list
the Java versions w/ SDK.

Ramin

**Comment by carlosmontenegrodeveloper1** [comment]
Hello Ramin.
The result is this (see the image). but version 8.0.265.hs-adpt.

![sdkman java list](https://user-images.githubusercontent.com/57047653/97912025-d3344600-1d11-11eb-89a4-60d68a8be614.png)
