### ISSUE TITLE
Opal logout does not trigger the expected session closure in Keycloak

### ISSUE THREAD

**Issue by IvoLeist** [obiba/opal#3598]
Dear Opal developers,

thank you for being so helpful in the past :)
We indeed decided to use Opal in a web application for biomedical research
as part of the 3TR project (https://3tr-imi.eu/)

This time we file the issue in your main repo 
because we do not think that the bug(?) is connected to the dockerization.
If it is I can move it to docker-opal.

**To Reproduce**
So this is what we observing when using Keycloak as identity provider:
Login works as expected, however when login out the Opal session in Keycloak is not closed 
meaning it is possible to sign in again on pressing on "Sign in with Keycloak" w/o the need to enter any credentials.
I hope that description is clear, if not let us know so I could record a gif for you.

**Expected behavior**
When using Keycloak as identity provider:
Pressing the logout button in Opal should close the Keycloak session.
Forcing the user to reenter the credentials when login again.

**Tested Browsers:**
 - Brave 1.16
 - Chromium 85.0
 - Firefox 82.0

Please let us know if the described behavior is a bug
or if we have to change some configuration etc.

Best regards,
Ivo

**Comment by ymarcon** [comment]
This is not a bug, it is a new feature request: having a single sign-out. This can potentially affect the behavior of other applications using the same OIDC provider (Keycloak in your case).

**Comment by IvoLeist** [comment]
Thank you for the quick clarification and addition to the EuCanConnect to-do list. We are aware that adding single log out may affect other applications. However, at this stage we have only Opal in that realm so that is no problem for us.

**Comment by ymarcon** [comment]
Tested with Keycloak.
