### ISSUE TITLE
Directory OPAL_HOME not created

### ISSUE THREAD

**Issue by vincentvanhees** [obiba/opal#3599]
I am trying to set up my first Opal data warehouse for use with Datashield on an Amazon virtual machine.

First I went through the Opal [installation process](http://opaldoc.obiba.org/en/latest/admin/installation.html) for [Debian package](https://www.obiba.org/pages/pkg/). After completion I type
`opal --help` which shows the opal documentation, so I assume the installation went well.

I am now continuing with the configuration step: http://opaldoc.obiba.org/en/latest/admin/configuration.html
There it reads "The file OPAL_HOME/conf/opal-config.properties is to be edited to match your server needs."
However, the directory OPAL_HOME does not exist for me.

```
$ find . OPAL_HOME
.
./.sudo_as_admin_successful
./.profile
./.cache
./.cache/motd.legal-displayed
./.bashrc
./.ssh
./.ssh/authorized_keys
./.viminfo
./.bash_logout
find: ‘OPAL_HOME’: No such file or directory
```

Does this mean that my Opal installation somehow failed?
If yes, could it be that I am using the wrong kind of environment? I am now using Amazon Lightsail which is a virtual machine with the following properties: Ubuntu 20, 8GB RAM, 2 vCPUs and 160GB SSD.

**Comment by vincentvanhees** [comment]
sorry, my mistake. I need to learn about how these Amazon virtual machine work. It is not a Opal issue.

**Comment by ymarcon** [comment]
When installed using debian package, the OPAL_HOME is /var/lib/opal, but you do not need to worry about that, just manage the app as a service `service opal start` or `systemctl start opal`.

**Comment by vincentvanhees** [comment]
@ymarcon sorry, one more question. When I do this it presents me with:

```
ubuntu@ip-172-31-37-1:~$ systemctl start opal
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'opal.service'.
Authenticating as: Ubuntu (ubuntu)
Password:
```

After filling in the password that I created during opal installation I get:

```
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
==== AUTHENTICATION FAILED ===
Failed to start opal.service: Access denied
See system logs and 'systemctl status opal.service' for details.

```

So, I then look up the status and see:

```
ubuntu@ip-172-31-37-1:~$ systemctl status opal.service 
● opal.service - LSB: Opal server
     Loaded: loaded (/etc/init.d/opal; generated)
     Active: active (exited) since Thu 2020-11-26 14:09:17 UTC; 1h 13min ago
       Docs: man:systemd-sysv-generator(8)
      Tasks: 0 (limit: 19204)
     Memory: 0B
     CGroup: /system.slice/opal.service

Nov 26 14:09:17 ip-172-31-37-1 systemd[1]: Starting LSB: Opal server...
Nov 26 14:09:17 ip-172-31-37-1 opal[32641]:  * Starting opal opal
Nov 26 14:09:17 ip-172-31-37-1 opal[32641]:    ...done.
Nov 26 14:09:17 ip-172-31-37-1 systemd[1]: Started LSB: Opal server.
Nov 26 14:09:17 ip-172-31-37-1 opal[32651]: opal: client (pid 32652) exited with 1 status
```

My password is fairly simple, so I am puzzled what the problem is. Should I just repeat the whole installation process and use an even simpler password?

**Comment by kazoompa** [comment]
Hi,

You need to be a sudo-er or root user to start a service. If `ubuntu` is a
sudo-er you can do:

```
sudo systemctl start opl   # use the ubuntu password
```

If `ubuntu` is not a sudo-er, ask your admin to make it a sudo-er. (FYI: How
To Add User To Sudoers
<https://phoenixnap.com/kb/how-to-create-sudo-user-on-ubuntu>)

Best,
