### ISSUE TITLE
CannotGetJdbcConnectionException

### ISSUE THREAD

**Issue by gerhardmayer-UKU** [obiba/opal#3605]
**Describe the bug**
After installing OPAL 3.0.7 with docker-compose I can login to OPAL and get the message
"No identifiers database is defined".
Then I registered my existing MySQL identifiers database.
When testing the connection I get a CannotGetJdbcConnectionException error,
see attached screenshot.

I used Ubuntu 20.04 LTS

![No connection to identifiers database](https://user-images.githubusercontent.com/69151299/104590311-6e7b5d00-566b-11eb-8dad-870ed11da9dc.PNG)

**Comment by ymarcon** [comment]
If opal is running in a docker container, the mysql server is certainly not running in localhost. You need another container with a mysql database for the ids.
By the way a database for the IDs is not a requirement, it is only necessary when mapping participant IDs at import/export time.

**Comment by kazoompa** [comment]
If you wish to use the MySQL server on your server you can get inspired by [this response](https://stackoverflow.com/questions/44543842/how-to-connect-locally-hosted-mysql-database-with-the-docker-container).
