### ISSUE TITLE
No error or warning when data can't be imported from R to OPAL

### ISSUE THREAD

**Issue by M-Driessen** [obiba/opal#3611]
**Describe the bug**
We came across an issue where we did not get a warning or error when uploading repeated data with the attribute 'opal.repeatable' = 0 from R. It caused quite some confusion before we found that the variable had the setting opal.repeatable set to 0 and that this was causing data to go missing.  It would be great if this could be added.

**To Reproduce**
Here is a small example script. The date is set to non-repeatable, and hence only the first date will be imported to OPAL. there is no warning or error saying that the second date cannot be imported.

test_data <- tibble(
  id = c(1,2,3,3),
  sex = c("M","F","M","M"),
  date = c(as.Date("2020-01-01"),as.Date("2020-01-02"),as.Date("2020-01-03"),as.Date("2020-01-04"))
)

attr(test_data$date, 'opal.repeatable') <- '0'

opal.table_save( opal = o, 
                 project = "test",
                 tibble = test_data, 
                 table = 'test_data', 
                 overwrite = TRUE, 
                 force = TRUE
)

**Expected behavior**
There should be a warning or error saying that data is not being imported properly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/79575366/108997005-67e6f900-769f-11eb-997b-15a413027951.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 88.0.4324.150

**Comment by ymarcon** [comment]
It is a feature of opal that some variable can be non-repeatable even when there are multiple rows in data imported. For instance the sex or the birth date usually do not change, so there is no point at making complex summary statistics on repeatable variables when it is not relevant. The side effect is that you must be careful with the `opal.repeatable` attribute because opal will not make any assumptions.

You might have a look at this release note: https://www.obiba.org/pages/news/release/opal/2.7/

**Comment by M-Driessen** [comment]
Ah, so it's explicitly meant this way as a feature. I can see it's uses, but it does indeed make operations tricky when combining tables on different levels. Data will in some cases be non repeatable on one end, but repeatable on the other. Thank you for your response, I'll make sure to be extra careful with this feature.

**Comment by ymarcon** [comment]
By default, when some multiple lines are detected (several rows for one entity ID), all variables are considered as being repeatable, i.e. you do not need to specify it. In your case you enforced the repeatable property and got what you asked :)
