### ISSUE TITLE
"Create table from dictionary" error goes unnoticed

### ISSUE THREAD

**Issue by gflcampos** [obiba/opal#3614]
When creating a table using a dictionary, if there is an error such as:
```
Exception for SQL []; SQL state [null]; error code [0]; liquibase.exception.DatabaseException: Incorrect string value: 
'\xE2\x89\xA548 ...' for column 'value' at row 1 [Failed SQL: INSERT INTO `opal`.`variable_attributes` (`datasource`, 
`value_table`, `variable`, `name`, `locale`, `namespace`, `value`) VALUES ('omitted', 'omitted', 'omitted', 'omitted', 'omitted', '', 
'omitted')]; nested exception is java.sql.SQLException: liquibase.exception.DatabaseException: Incorrect string value: 
'\xE2\x89\xA548 ...' for column 'value' at row 1 [Failed SQL: INSERT INTO `opal`.`variable_attributes` (`datasource`, 
`value_table`, `variable`, `name`, `locale`, `namespace`, `value`) VALUES ('omitted', 'omitted', 'omitted', 'omitted', '', 'omitted')]
```

in the Opal log, the error is not noticeable for the web client. There is no error shown to the client and it appears that the table was created successfully. Later, this will cause errors when trying to import data into the table.

**Comment by ymarcon** [comment]
Could you provide steps to reproduce?

**Comment by gflcampos** [comment]
Here: [mytable.zip](https://github.com/obiba/opal/files/6171763/mytable.zip)

The `≥` in the dictionary causes the error I reported above. I must say that the error occurred on one machine but not on another (both with Opal 3.0.9). Regardless, the point is that, <ins>if</ins> there is an error like this one, the client will not know.

**Comment by ymarcon** [comment]
As you said it is hard to reproduce. Do you have the corresponding log lines so that I can identify where the SQLException is caught and ignored?

**Comment by gflcampos** [comment]
Here is the complete trace:
[dict_error.log](https://github.com/obiba/opal/files/6310800/dict_error.log)
