### ISSUE TITLE
Execute SQL queries on a project's tables

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3616]
It would be useful to be able to run SQL queries on a datasource, as examples:

```
select * from CNSIM1
select * from CNSIM1 union all select * from CNSIM2
select avg(LAB_HDL) as hdl_avg, GENDER as gender from CNSIM1 where LAB_HDL is not null group by GENDER
select avg(LAB_HDL) as hdl_avg, PM_BMI_CATEGORICAL as bmi from (select * from CNSIM1 union all select * from CNSIM2) where PM_BMI_CATEGORICAL is not null group by PM_BMI_CATEGORICAL
``` 

This will allow to interface with systems that do SQL queries, such as [Redash](https://redash.io/).

**Comment by ymarcon** [comment]
REST entry point is per-project datasource:

```
POST /datasource/xxx/_sql[?id=_id]
```

where the body is the SQL query and the `id` parameter is the name of column of identifiers (default is `_id`).

**Comment by slaverman** [comment]
> It would be useful to be able to run SQL queries on a datasource, as examples:
> 
> ```
> select * from CNSIM1
> select * from CNSIM1 union all select * from CNSIM2
> select avg(LAB_HDL) as hdl_avg, GENDER as gender from CNSIM1 where LAB_HDL is not null group by GENDER
> select avg(LAB_HDL) as hdl_avg, PM_BMI_CATEGORICAL as bmi from (select * from CNSIM1 union all select * from CNSIM2) where PM_BMI_CATEGORICAL is not null group by PM_BMI_CATEGORICAL
> ```
> 
> This will allow to interface with systems that do SQL queries, such as [Redash](https://redash.io/).

We are currently trying to create a dashboard in Redash using the REST entry point described in this issue. However it is not possible in Redash to post a plain text body (only form-data or JSON), see https://redash.io/help/data-sources/querying/json-api and the screenshot below. In the post above you mentioned "_This will allow to interface with systems that do SQL queries, such as Redash_". How did you envision to use Redash in combination with the SQL REST endpoint?

![image](https://user-images.githubusercontent.com/19187321/124599903-7b347d00-de66-11eb-954e-f72cf7a2114c.png)

**Comment by ymarcon** [comment]
The idea is more to develop a custom Redash Data Source. The JSON Data Source that you are proposing to use does not have the flexibility of the SQL.

**Comment by ymarcon** [comment]
FYI you may be interested in the discussion thread "Creating a new query runner (data source) in Redash":
https://discuss.redash.io/t/creating-a-new-query-runner-data-source-in-redash/347

**Comment by ymarcon** [comment]
Excellent! I completely agree with having a real pip library. 

Type guessing can be done by getting the table dictionary at `/datasource/{project}/table/{table}/variables`.

**Comment by slaverman** [comment]
> Excellent! I completely agree with having a real pip library.
> 
> Type guessing can be done by getting the table dictionary at `/datasource/{project}/table/{table}/variables`.

It is a hassle to extract each table name from a query with a lot of tables joined together and then extract the selected column names per table (especially with all columns selected with *, if column names are renamed or a function is applied). Including datatypes in columns (in response) would be a lot easier.

Btw, is it true that aliases for table names are not supported by the SQL API?

**Comment by ymarcon** [comment]
Right, without a proper SQL parser that is not possible to identify tables and variables. And anyway, the data dictionary is useless when applying a SQL function transformation. I noticed that the JSON output was not correct regarding data types, see #3661, it's fixed.

Regarding table alias, the table name detection is now more restrictive, see #3662.
