### ISSUE TITLE
Error when launching docker-opal

### ISSUE THREAD

**Issue by ESCRI11** [obiba/opal#3620]
I'm using the docker-compose.yml from docker-opal and I'm getting an error with the Rock container.

I have installed the suggested versions of the documentation.

Procedure used:
- Cloned docker-opal (https://github.com/obiba/docker-opal)
- Run `docker-compose -f docker-compose.yml up`

Error:
```
rock_1          | 2021-04-08 07:42:09,592 - ERROR - org.springframework.boot.SpringApplication - Application run failed
rock_1          | org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
rock_1          | found character '@' that cannot start any token. (Do not use @ for indentation)
rock_1          |  in 'reader', line 38, column 15:
rock_1          |           secret: @rock_administrator_password@
rock_1          |                   ^
```

I'm trying to run the containers through an Ubuntu running on WLS2.

Any idea where I can start debugging?

**Comment by ymarcon** [comment]
This docker-compose example is not complete, see documentation at:
https://rockdoc.obiba.org/en/latest/admin/installation.html#docker-image-installation

**Comment by ESCRI11** [comment]
That makes sense. Thanks for the quick reply.
