### ISSUE TITLE
Opal fails to recognise a composite primary key while importing data (Tabular SQL)

### ISSUE THREAD

**Issue by abhishekdxt** [obiba/opal#3633]
Let us suppose there is a table 'patient_signals' with 4 columns - id, signal_id, opal_created, opal_updated.

In this table columns 'id' and 'signal_id' is together defined as PRIMARY KEY (PK).

Adding a single column PK is not a good solution for the reasons stated below:

1) the original data structure is violated  (entity is no more repeatable)
2) Opal front-end is unable to treat 'signal_id' as a repeatable variable

I see the following error in the prepared statement when I try to update (i.e. incremental import) the table:

org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [UPDATE `patient_signals` SET `opal_updated` = ?, `signal_id` = ? WHERE `id` = ?]; Duplicate entry '9rYe077-icp' for key 'patient_signals.PRIMARY'; nested exception is java.sql.BatchUpdateException: Duplicate entry '9rYe077-icp' for key 'patient_signals.PRIMARY'.

It is evident that a correction in WHERE clause will fix the problem. 

I have also tried non incremental import and that works provided the PK constraint is not violated i.e. the combination of 'id' and 'signal_id' is not already present. It is a simple case of INSERT statement not requiring a WHERE clause.

Is it possible to fix this? One simply has to use the PKs in WHERE clause (UPDATE statement).

SHOW KEYS FROM patient_signals WHERE key_name = 'PRIMARY'; 

Thank you

**Comment by ymarcon** [comment]
Is it a SQL table that you are trying to import?

**Comment by abhishekdxt** [comment]
Yes a SQL table. It will be really helpful if Opal can allow CRUD operations on table(s) with composite primary key.

**Comment by ymarcon** [comment]
If it is an import, it is a copy (only the R in the CRUD).

I don't think Opal will handle composite keys in a near future, unless you want to fund this feature.

**Comment by abhishekdxt** [comment]
Okay thanks. Could you tell me what is the difference between MySQL 'export' and 'import'  database type.

I understand the 'storage' type only allows one PK per table.

**Comment by ymarcon** [comment]
Export is also a copy, whether it is a CSV file or a SQL table, the process is the same. One primary key in Opal also means one primary key in the export media.

**Comment by abhishekdxt** [comment]
I configured my MySQL database as type 'export' and Opal does recognise composite primary key.
The repeatable column is also rendered correctly.
The problem is only in the UPDATE statement as explained above (INSERT operation also works).

When the type is storage only then Opal drops the other PK i.e. single key 'opal_id' is retained.

**Comment by ymarcon** [comment]
This is a side effect. Composite keys are not supported.

**Comment by abhishekdxt** [comment]
A positive and desirable side effect :) Can we please leave this side effect as it is?

What we are going to do is to use Opal for plug-n-play i.e. run queries, create views and export data.

We will make the CRUD operations outside Opal.

**Comment by abhishekdxt** [comment]
I have also noticed that with 'Export' type Opal is unable to create a MySQL table because the datasource (name) placeholder is missing.

**Comment by abhishekdxt** [comment]
I have managed to fix the missing datasource (name) by setting the default value for 'datasource' column in all Opal specific tables namely value_tables, variables, variable_attributes, categories and category_attributes.

Because these tables reside within a single MySQL schema/project (Opal project) so the datasource column is always going to have the same value (hence default).  The composite PK also works and the Opal front-end renders it nicely. 

Just to re-iterate this set-up only works with 'Export' database type.
