### ISSUE TITLE
import du csv depuis opal vers R studio utilisant la fonction opal_file_download()

### ISSUE THREAD

**Issue by GuiFabre** [obiba/opal#3638]
**Describe the bug**
- un fichier au format CSV ne peut pas etre importé dans un environnement R en utilisant la fonction opal_file_download()
- ce fichier est fonctionnel et peut etre lu sur EXCEL ou bien depuis R avec la fonction read_csv
- si ce fichier est appelé mon_fichier.csv2 au lieu de mon_fichier.csv, alors il ny a pas de probleme.

**To Reproduce**
1. Go to '...' opal version 4.1.1
2. Click on '....' mettre le fichier dans un folder (mon_fichier.csv)
3. copier ce fichier et l'appeler mon_fichier.csv2 (pour comparaison)
4. aller dans Rstudio et utiliser la fonction de opalr (2.1.0) opal.file_download

**Expected behavior**
devrait telecharger les deux fichiers comme attendu

**Screenshots**
![image](https://user-images.githubusercontent.com/51246435/120036896-cd17f680-bfce-11eb-9372-044ee7a7cc36.png)

**Additional context**

**Comment by meek0** [comment]
After some testing, this seems to be related to obiba/opalr's opal.file. For some reason, the content is not read correctly. Need to investigate further.

**Comment by ymarcon** [comment]
I cannot reproduce with the following script:

```
library(opalr)
o <- opal.login(username = "administrator",
                password = 'password', 
                url = 'https://opal-demo.obiba.org')
opal.file_upload(o, "/path/to/file.csv", "/tmp")
opal.file_ls(o, "/tmp")
opal.file_download(o, "/tmp/file.csv")
opal.logout(o)
```

* Please try with verbose option:

```
options(verbose = TRUE)
```

you should see messages like

> <- HTTP/1.1 200 OK
> <- Date: Sun, 30 May 2021 18:44:36 GMT
> <- Server: Apache/2.4.41 (Ubuntu)
> <- X-Opal-Version: 4.1.3
> <- Expires: Thu, 01 Jan 1970 00:00:00 GMT
> <- Allow: DELETE, POST, GET, PUT, OPTIONS
> <- Cache-Control: no-cache
> <- Content-Disposition: attachment; filename="file.csv"
> <- Content-Type: text/csv

* Is your file in a specific encoding? Can you make a small csv test file that can be shared in this issue?

**Comment by ymarcon** [comment]
Fixed in opalr 2.1.1
