### ISSUE TITLE
New jfrog repo for opal (somewhat) broken

### ISSUE THREAD

**Issue by pmopmo** [obiba/opal#3646]
Hello!

The OBiBa RPM repository appears to be missing a file list (filelist.xml) in its repodata folder (https://obiba.jfrog.io/artifactory/rpm-local/repodata/). 

This makes Red Hat Satellite complain that it's not a valid repository
`Yum Metadata: Malformed repository: "filelists" metadata is not found in repomd.xml`

Could it be the case that the "Enable File List Indexing" option (https://www.jfrog.com/confluence/display/JFROG/RPM+Repositories#RPMRepositories-IndexingtheFileList) has not been enabled in Artifactory?

Many thanks in advance!

**Comment by ymarcon** [comment]
Done, thanks for the trick! It is a shame that this built-in repo does not have the option activated by default.

**Comment by ymarcon** [comment]
By the way I am in the process of refactoring the DEB/RPM packaging so that it is based on systemd. So if you encounter some issues, wait for the next release or use [docker](https://opaldoc.obiba.org/en/latest/admin/installation.html#docker-image-installation).
