### ISSUE TITLE
Permissions on Project

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3650]
Related: https://github.com/obiba/opal/issues/2155

**Is your feature request related to a problem? Please describe.**
In previous versions of Opal it was possible for a user to have the ability to create a view in project, even if they were not administrator. This features seems to have gone (I don't know exactly when).

This also impacts the ability of users to provide dictionaries that update variables for multiple tables at once.

Use case 1: A study uploads their data for us but doesn't create the view. Previously we could create the view and start work, now we have to email them to get them to do this for us. 

Use case 2: We have 20 studies in a project. We want to create a new variable in all of them via a dictionary. Now we have to do this individually for each study

**Describe the solution you'd like**
If a user has permission to edit dictionaries on a table in a project, they have the ability to create and delete a view on that project (but not manage permissions on it). Equally they can add variables to tables/views they have permission on using a dictionary file.

**Describe alternatives you've considered**
 Alternatively there should be the option to bulk create a variable across tables/views.

**Additional context**

**Comment by ymarcon** [comment]
Fixed: bulk addition/edition/removal of tables/views available to users with TABLE_ADD permission on a project. View values still hidden when underlying table has restricted access.
