### ISSUE TITLE
Large taxonomies lead to crash

### ISSUE THREAD

**Issue by paulusv** [obiba/opal#3654]
Hi,

In our project we uploaded a large taxonomy (vocabulary with +- 100.000 terms).
Now when we try to add an annotation (go to project -> tables -> edit annotation -> add annotation), the site crashes and get a 'not responding' popup. This makes it impossible to use the taxonomy.
We have downscaled the taxonomy to +- 100 terms, which seems to have resolved the problem.
However we would like to use the full taxonomy if possible.

Just in case, I used Google Chrome, Version 91.0.4472.114, without any plugins/extensions.

Best,
Paul

**Comment by ymarcon** [comment]
Could you share this large taxonomy privately? (you have my email I think)

**Comment by paulusv** [comment]
I've sent you an email!

**Comment by ymarcon** [comment]
Thanks, I can reproduce. Obviously browsers do not like the dropdown with thousands of entries... I will change it for an autocomplete/type-ahead widget.

**Comment by paulusv** [comment]
Thank you very much!

**Comment by ymarcon** [comment]
If you have the opportunity to test... I have adapted the taxonomy term selection dialog to the case of the vocabulary has a lot of terms (more than 200).

![image](https://user-images.githubusercontent.com/2581149/123419082-1baeb580-d5ba-11eb-9d2b-e3940d976aca.png)
