### ISSUE TITLE
New jfrog repo for opal (somewhat) broken #2

### ISSUE THREAD

**Issue by pmopmo** [obiba/opal#3656]
Hello again

We get these complaints from yum on redhat 7&8

> Package opal-python-client-4.1.1-1.noarch.rpm is not signed
> Package opal-server-4.1.4-1.noarch.rpm is not signed

I humbly ask that you sign the rpms when you build them

**Comment by ymarcon** [comment]
Repo index needed to be recalculated. Please try again.

**Comment by pmopmo** [comment]
I see no change

> $ wget -q https://obiba.jfrog.io/artifactory/rpm-local/opal-server-4.1.4-1.noarch.rpm
> $ rpm -qip opal-server-4.1.4-1.noarch.rpm
> Name        : opal-server
> Version     : 4.1.4
> Release     : 1
> Architecture: noarch
> Install Date: (not installed)
> Group       : Applications/Engineering
> Size        : 155645196
> License     : see /usr/share/doc/opal/copyright
> Signature   : (none)
> Source RPM  : opal-server-4.1.4-1.src.rpm
> Build Date  : Wed 02 Jun 2021 01:55:17 PM CEST
> Build Host  : travis-job-c61aedfb-1392-46b6-acdd-52156e434d1b
> Relocations : /usr/share
> Packager    : OBiBa
> Summary     : opal-server
> Description :
> Opal Application
> 

As you can se there is no **Signature**.

This is an annoyance as you have to do an extra step yo update the obiba packages  (--nogpgcheck flag for yum for example)
