### ISSUE TITLE
SQL API returns error for haven labbeled missings

### ISSUE THREAD

**Issue by slaverman** [obiba/opal#3658]
**Describe the bug**
The SQL API returns an error for tables with haven labelled user_missings. Both the haven and labbelled package are installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/19187321/124601625-5a6d2700-de68-11eb-95eb-e283eaee2fe4.png)
![image](https://user-images.githubusercontent.com/19187321/124603478-40344880-de6a-11eb-9cf8-f837f750cacd.png)
![image](https://user-images.githubusercontent.com/19187321/124603533-4de9ce00-de6a-11eb-8697-f1bd2bed2bb8.png)

**Comment by ymarcon** [comment]
Do you have a sample dataset to reproduce?

**Comment by ymarcon** [comment]
What if you upgrade haven to the latest version `2.4.1`?
Have you recently upgraded R base (to `4.1`)?

**Comment by slaverman** [comment]
> Do you have a sample dataset to reproduce?
See sample below. It seems that only the decimal dataype returns an error.

![image](https://user-images.githubusercontent.com/19187321/125249871-f7f7a900-e2f5-11eb-9b86-09f5b98e9e67.png)

![image](https://user-images.githubusercontent.com/19187321/125249919-0219a780-e2f6-11eb-9760-dd025ee471ec.png)


```{r}
project_name <- "TEST_PROJECT"
table_name <- "user_missing_test"
entity_type <- "Participant"


opal_connection <- opal.login(token = , url = )


data <- tibble::tribble(
  ~id, ~var_a, ~var_b,
  "1","-99",-99,
  "2","2",1
)

variables <- tibble::tribble(
  ~name, ~entityType, ~valueType, ~labe, ~unit, ~repeatable, ~index,
  "var_a", entity_type, "text", "Var A",  "", 0, 1,
  "var_b", entity_type, "decimal", "Var B",  "", 0, 2
)

categories <- tibble::tribble(
  ~variable, ~name, ~missing, ~label,
  "var_a", "-99", 1, "Missing",
  "var_a", "2", 0, "Test",
  "var_b", -99, 1,"Missing"
)

opal.table_save(
  opal_connection,
  data,
  project_name,
  table_name,
  overwrite = TRUE,
  force = TRUE,
  type = entity_type
)


opal.table_dictionary_update(
  opal_connection, 
  project_name, 
  table_name, 
  variables, 
  categories
)

opal.logout(opal_connection)

```

**Comment by ymarcon** [comment]
Have you tried on https://opal-demo.obiba.org (credentials: administrator/password) ?

**Comment by slaverman** [comment]
> Thanks. Have you tried on https://opal-demo.obiba.org (credentials: administrator/password) ? (I am traveling and can't do it myself)

I'm able to reproduce it on the demo version: 
![image](https://user-images.githubusercontent.com/19187321/125255400-aa7e3a80-e2fb-11eb-959b-d54a15a28363.png)

**Comment by ymarcon** [comment]
For the record, the R server log:

```
Loading required package: labelled
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'as.haven_labelled' of mode 'function' was not found
In addition: Warning messages:
1: no DISPLAY variable so Tk is not available 
2: In is(x) : restarting interrupted promise evaluation
```

**Comment by ymarcon** [comment]
Issue caused by the variable having *all* categories with *missing* flag. If at least one of the categories is not a _missing_ one, it works

**Comment by slaverman** [comment]
> Issue caused by the variable having _all_ categories with _missing_ flag. If at least one of the categories is not a _missing_ one, it works

Thanks for finding that out! Is this a bug or a feature?

**Comment by ymarcon** [comment]
A bug! but not necessarily in Opal... It may be in an R package issue. We'll need to find a workaround.
