### ISSUE TITLE
Giving permissions to a user is case sensitive

### ISSUE THREAD

**Issue by paulusv** [obiba/opal#3660]
When adding permissions to a user for viewing certain tables, the popup tool allows users to be selected which will gain access.
A list appears with users in the system, however it is also possible to give permissions to users which do not have an account yet. However, giving permissions seems to be case sensitive when matching the given user to the user database.

Example:
We use an identity provider, which makes sure that user names are known before a persons first login.
If we have a user, Arnold User, the identity provider will assign him the username "A.User".
We can give Arnold certain permissions before his first login, by inserting "A.User" as the user to receive permissions.
On his first login, his username will be matched and he'll gain the right permissions.
However, if someone gives "a.user", "a.User" or "A.user" permissions, Arnold will not receive any permissions ("A.User" will not appear in the dropdown list since he has not logged in yet).

Ideally Arnold would still receive his permissions, disregarding whether no or bad casing is applied. It would be great if there is a option for giving permissions where case is ignored. Otherwise, it would be great if there was an option (e.g. a checkbox) when creating an identity providers to convert usernames to lowercase, and an option (again a checkbox) to use lowercase names when giving permissions to certain users.
This way, it would be possible to give the permissions to "A.User" with "a.user".

**Comment by kazoompa** [comment]
I personally believe the usernames should respect the case sensitivity for authentication and permissions. Opal User ACL Table needs to map the proper username (case-sensitive) to the given permissions.

**Comment by ymarcon** [comment]
I am not in favor of having case insensitive permissions, it has too much implications in terms of security.
The other option would be to transform the username received from the ID provider.
For now, you can (1) grant permissions per group, (2) configure the ID provider's groups using an appropriate javascript ([Groups Mapping by Javascript](https://opaldoc.obiba.org/en/latest/web-user-guide/administration/identity-providers.html#add-id-provider)).

**Comment by paulusv** [comment]
Okay, thanks for the quick response!
