### ISSUE TITLE
Adding option to send email on report fails

### ISSUE THREAD

**Issue by paulusv** [obiba/opal#3663]
The option to email a user a generated report is extremely useful, especially with the use of scheduled reports.
However, since can data change over time, or report template become outdated, it can occur that scheduled reports will not finished due to a bug.

It would be nice if there was an option to send an email (maybe only for scheduled reports), when a report fails to be generated.
This way people do not have to rely on looking at the logs to see whether reports have failed.

**Comment by ymarcon** [comment]
Would you like to define a different list of recipients to notify when the report generation fails?

**Comment by paulusv** [comment]
In our use case, we only need the option to send an email when a report fails (not on succession).
For a more general usage, I think your suggestion might be best. So something like a separate option field 'send email on failure to'.
