### ISSUE TITLE
CentOS systemd not working

### ISSUE THREAD

**Issue by mennodekker** [obiba/opal#3665]
The OPAL_DIST variable is not expanded but used as readlink etc. causing the opal service not to start on CentOS

Final command to start is:
`/usr/bin/java -Xms1G -Xmx2G -XX:+UseG1GC -cp '/var/lib/opal/conf:$(readlink -f /usr/share/opal)/lib/*' -DOPAL_HOME=/var/lib/opal '-DOPAL_DIST=$(readlink -f /usr/share/opal)' -DOPAL_LOG=/var/log/opal org.obiba.opal.server.OpalServer
`
I created a pull request to fix this:
#3664

**Comment by ymarcon** [comment]
Please have a try with opal 4.2.3

**Comment by mennodekker** [comment]
Sorry, it does not seem work... maybe I setted the variable locally and it worked because of that and not the change in the script. It must be that the user is not allowed to execute or something like that. I will experiment and see if I can find something.
