### ISSUE TITLE
Proxy configuration not working on docker

### ISSUE THREAD

**Issue by SirHerr** [obiba/opal#3687]
Hi guys, we deployed opal version 4.1 on a server behind a firewall for productive use. However, whenever we set proxy parameters either on the host, the docker daemon, or as environment variables mounted to the container, the opal client is not using it. Therefore opal cannot communicate to the identity provider in a different domain. Any ideas how I can set it properly?

**Comment by ymarcon** [comment]
Hi, I am not sure I understand your setup but you can have a look at
https://opaldoc.obiba.org/en/latest/admin/configuration.html#reverse-proxy-configuration

**Comment by SirHerr** [comment]
We have two VMs in different network domains with different settings: on one VM is Keycloak and a reverse proxy and on the other VM all opal / rock / mongo services.

A request to opal will go to a reverse proxy on VM 1 and will be forwarded to the internal domain zone. Within opal I configured Keycloak as identity provider. I can successfully log in using Keycloak, but the roles of the users are not forwarded (on a test machine outside it is working). This was only possible, after I set the Keycloak IP & Url as a workaround directly within the hosts file.

Based on this outcome we started discussions with the firewall team. The feedback was that the opal service is trying to communicate without using the proxy. Therefore I tried to set the https proxy as java_opts, docker proxy and host environment settings. Everything I tested is communicating using the proxy, except the opal java vm.

Is it possible, that the java opts are not forwarded to opal? When I run  inside the opal container a test script for the internet connection with `java ${JAVA_OPTS} test` it is possible, but not without the options.

**Comment by SirHerr** [comment]
This is within the opal logs:
````Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2152) ~[na:1.8.0_242]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[na:1.8.0_242]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570) ~[na:1.8.0_242]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[na:1.8.0_242]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[na:1.8.0_242]
        at java.net.URL.openStream(URL.java:1068) ~[na:1.8.0_242]
        at org.obiba.opal.web.system.news.ObibaNewsYaml.loadNews(ObibaNewsYaml.java:27) ~[opal-core-ws-4.1.4.jar:na]
        at org.obiba.opal.web.system.SystemResource.getNews(SystemResource.java:77) ~[opal-core-ws-4.1.4.jar:na]
        ... 61 common frames omitted
2021-12-02 10:51:20,188 ERROR org.obiba.oidc.web.filter.OIDCLoginFilter - OIDC login request to 'keycloak' failed.
org.obiba.oidc.OIDCException: Cannot get OIDC provider metadata for keycloak
        at org.obiba.oidc.OIDCConfiguration.findProviderMetaData(OIDCConfiguration.java:72) ~[obiba-oidc-1.15.4.jar:na]
````
The proxy credentials and configs are fine.

**Comment by ymarcon** [comment]
If you look at the opal's docker log output, you should see the `JAVA_OPTS` echoed at startup. Something like this:

```
opal_1           | Waiting for Opal to be ready...
opal_1           | JAVA_OPTS=-Xms1G -Xmx2G -XX:MaxPermSize=256M -XX:+UseG1GC
opal_1           | OPAL_HOME=/srv
opal_1           | OPAL_DIST=/usr/share/opal
```

**Comment by SirHerr** [comment]
Yes here it shows me all -Dhttp.proxyHost / User / Password / & Port configs properly

**Comment by ymarcon** [comment]
The issue is that the proxy user and password settings are not automatically handled by java, on the contrary of the proxy host and port. Opal server does not have proxy support, this is a feature request. It would not be difficult to implement I think, but we do not have a proper testing environment.

**Comment by SirHerr** [comment]
Thanks for the response! I will try to find a way to get around using user and password.

**Comment by ymarcon** [comment]
Well, if you want to collaborate I can implement the feature and make a docker image to test.

**Comment by SirHerr** [comment]
Would be great! I got a system account and could connect  the proxy without the username and password. Only the roles a not mapped correctly. Could be due to nginx or firewall settings. Outside on develop VMs everything works with group permissions, so the problem cannot be the keycloak instance. Additionally the R server is not available anymore after making proxy changes.

**Comment by ymarcon** [comment]
Regarding Keycloak, if the UserInfo object contains all the necessary group information, you can map this JS object to group name(s). See "Groups Mapping by Javascript" at:
https://opaldoc.obiba.org/en/latest/web-user-guide/administration/identity-providers.html#add-id-provider

**Comment by ymarcon** [comment]
Please have a try with image `obiba/opal:snapshot`.

**Comment by ymarcon** [comment]
Any feedback to share about the snapshot image and the proxy credentials handling?

**Comment by ymarcon** [comment]
Try with opal 4.3.1. Please feel free to reopen if not expected behavior.

**Comment by SirHerr** [comment]
Hey Yannick, sorry for the extremely late response. I had many issues figuring out that the proxy was still not working properly, even if the logs showed it seemed to work. Unfortunately, the redirects back to the application from Identity Providers are ending up in time-out errors. After looking into your [commit](https://github.com/obiba/opal/blob/b501752c5d28d4ccd93e940d4609aa848328cec3/opal-server/src/main/java/org/obiba/opal/server/OpalServer.java#L61) I request two minor changes: is it possible to define an ALWAYS_PROXY option and include the no_proxy as java_opts? The ALWAYS_PROXY could be included within the if condition in line 61 as `getRequestorType() == Authenticator.RequestorType.PROXY || Sytem.getProperty('ALWAYS_PROXY') == true` or similar 🙃 would be great to use opal productive with identity providers to have a central user administration 😊
