### ISSUE TITLE
Possibility to disable username/password authentication for R access (only)?

### ISSUE THREAD

**Issue by bjornwiberguuse** [obiba/opal#3691]
If I interpret the documentation (https://opaldoc.obiba.org/en/dev/r-user-guide/r.html) correctly, Opal R access (authentication) can be performed using username/password credentials, key credentials or Personal Access Tokens.

_Would it be possible to disable username/password authentication for R access **only**, while still allowing it for the rest of Opal (the web interface)?_

This would be desired to avoid username/password credentials being present in R code, e.g. in case the Opal account has (much) broader access to the content in Opal than what the Personal Access Token allows for.

**Comment by ymarcon** [comment]
I understand your request but practically it would mean that the auth process API would discriminate connections from regular web browsers versus ones from scripts (whatever language). The [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) provides this information, but... it is not reliable at all (see for instance [How to fake and rotate User Agents using Python 3](https://www.scrapehero.com/how-to-fake-and-rotate-user-agents-using-python-3/)).

What I suggest instead is to enable 2-factor-authentication when credentials are username/password. That would apply to any client (browser or application). Human intervention would be required when using username/password; automated connections (from a script or any other app) would make use of PAT. I plan to add the 2FA feature in the next release of Opal.

**Comment by bjornwiberguuse** [comment]
Hello Yannick!

Thank you for your reply!

Actually we're using a web server managed authentication method (Shibboleth SP / shibd / mod_shib for Apache) as a second factor (of some sort), which is sitting in front of Opal.

However Opal does not have the ability to pick this information up (from a REMOTE_USER environment variable), I believe, so after logging in through the web server, one has to log in to Opal, too, with manually assigned Opal usernames/passwords.

Currently we have openings (we disable the web server managed authentication method) for /ws/, which of course is suboptimal from a security perspective; otherwise R access would not be possible at all.

So, our desire to disable username/passwords for R access stems from our current usage of username/passwords, which stems from our usage of a (by Opal) non-supported authentication method...

Perhaps that would be another feature request for the future (supporting web server managed authentication, so that any authentication method supported by the web server can be used with Opal)?

**Comment by ymarcon** [comment]
See #3710
