### ISSUE TITLE
Problem with id's consisting of leading zeros

### ISSUE THREAD

**Issue by M-Driessen** [obiba/opal#3693]
**Describe the bug**
running into this error:
Error: Import of "/home/user/R/5630377/file20c81daa1775.rds" ended with status: FAILED

Traced the problem back to id's with leading zeros.
When there is one id that does not start with a 0, everything is fine, but when they all have leading zeros the error pops up.

**To Reproduce**
library(tidyverse)
library(opalr)

data <- tibble(
  id = c("01","02"),
  var1 = c(5,6),
  var2 = c("a","b")
)

o <- opal.login(token = , url = )

opal.table_save(
  o,
  data,
  "TEST",
  "Test",
  overwrite = TRUE,
  force = TRUE,
  type = "Participant"
)

opal.logout(o)

**Expected behavior**
Expected the data to be saved normally, but somehow the leading zeros cause problems.
When there is one id that does not start with a zero, the problem is gone. 
Since we import data from other sources where the id's are already specified, we can't really change the id's or remove the leading zeros.

**Desktop (please complete the following information):**
Windows 10
Opal version 4.2.8
opalr version 3.0.2

**Comment by ymarcon** [comment]
I suspect R somehow converts ids into numerics. I will check that.

**Comment by M-Driessen** [comment]
When the id's are numeric R trims the zeros and the problem disappears.

data <- tibble(
id = c(01, 02),
var1 = c(5,6),
var2 = c("a","b")
)

This will save without a problem. 
When it's a character string it gives the error

**Comment by ymarcon** [comment]
I can reproduce locally and this is an issue with the R's `tibble` package: it works with `tibble 3.0` and it breaks with `tibble 3.1`. I will check why.

**Comment by ymarcon** [comment]
Fix available in version 4.3.2.

**Comment by M-Driessen** [comment]
Thank you!
