### ISSUE TITLE
CSFR warning in release 4.3 / no login possible

### ISSUE THREAD

**Issue by 226k** [obiba/opal#3703]
Dear all,
we are trying to set up the new Opal/Datashield release via apt. 
While the installtion itself works fine (except that the installer asks for the administrator PW but does not check wether it  succeeds the security rules or not), we are not able to log in afterwards.

Log into Opal is possible when we are using 127.0.0.1:8080/8443 by tunneling the ports via ssh from the Opal-VM to our desktop pc. As soon as we try to login via IP:8080 or IP:8443 or via an DNS-name/Alias/whatever:8080 or 8443 the frontend tells "Authentication failed" and the logs print "WARN org.obiba.opal.web.security.CSRFInterceptor - CSRF detection".
There is no difference when putting a proxy before (like our final setup has to; are there best-practise-suggestions for nginx?) or accessing the VM directly via IP adress.

Can we deactivate the CSRF checks?

Best
Sascha

**Comment by 226k** [comment]
Thanks for the hint - we use that option too, as well as 
`proxy_pass_header Set-Cookie` (what google told me to use :) )

Unfortunately, the login-error and CSFR warning also appears without the use of a proxy, only after installing Opal on a VM and accessing the machine directly via its IP (https://123.123.123.123:8443, http://123.123.123.123:8080) or using its alias (given by our DNS Server, e.g. https://datashield.our-intra-domain.de:8443 or http and 8080). 
The only way a login works is ssh-ing into the VM with forwarding port 8443 to a local port (e.g. 9443) ('ssh IP-of-datashield -L 9443:IP:8443') and then accessing https://127.0.0.1:9443 in the browser.

**Comment by ymarcon** [comment]
Thanks for the report.
I'll make a quick setting for deactiving the CSRF check, in the next patch release. 
On the long term, I'll make the CSRF check more configurable as well.

**Comment by ymarcon** [comment]
I am not sure, it is a network thing. The warning message informs you about the origin of the request from opal (=java net api) point of view.

**Comment by ymarcon** [comment]
Please try with Opal 4.3.3.

**Comment by ymarcon** [comment]
See documentation:
https://opaldoc.obiba.org/en/latest/admin/configuration.html#cross-site-resource-forgery-csrf
