### ISSUE TITLE
Proxy settings minor adaption

### ISSUE THREAD

**Issue by SirHerr** [obiba/opal#3705]
Based on the previous [issue](https://github.com/obiba/opal/issues/3687#issuecomment-1074335803) I would like to request two minor changes: an always proxy environment option and parsing the -Dhttp.nonProxyHosts Java_Opts.

**Comment by SirHerr** [comment]
Our proxy server does not expose itself as proxy server, such I need to set the proxy header manually.

**Comment by ymarcon** [comment]
The problem is that I do not have the possibility to test such feature. Are you able to run opal in a docker image? If yes, I can provide a snapshot image, and you can do the testing (I'll add log messages).

**Comment by SirHerr** [comment]
Yes I deployed opal via docker and can test the feature! Thank you!

**Comment by ymarcon** [comment]
ok give a try to image `obiba/opal:snapshot` and let me know what's in the log output. I have added a property `requestorType` which values can be `proxy`, `server` or `any`.

**Comment by SirHerr** [comment]
Thanks - I tried to start it, but its not taking the `requestorType` correctly (. Most likely my fault: shall I set is as JAVA_OPTS or environment? Here a screenshot of the logs (where it is not using it properly):
<img width="475" alt="Bildschirmfoto 2022-03-29 um 12 32 43" src="https://user-images.githubusercontent.com/10449223/160592890-f039ed7f-63a3-4683-b4ba-5706a880794d.png">

**Comment by ymarcon** [comment]
Please get the application's log, not just the stdout. You can download the **Server logs** from the _Administrator / Java Virtual Machine_ page.

**Comment by SirHerr** [comment]
Thanks! I could not find any requestorType, requestingProtocol, requestingHost or similar strings related to the proxy within the logs.

**Comment by ymarcon** [comment]
there will be log messages only if the http.proxyUser (or https.proxyUser) is defined and when the Authenticator.getPasswordAuthenticaiton() is called, see https://github.com/obiba/opal/commit/0b7d7a17a66f5ca31e57d79657edbadafc0bbb73

**Comment by SirHerr** [comment]
The http.proxyUser, Host, Port and User (also the unused nonProxyHosts) are defined via the JAVA_OPTS. But it does not show more information in the java logs regarding proxys.

**Comment by ymarcon** [comment]
Then that means that java does not call for the Authenticator.
