### ISSUE TITLE
Problem with new password policy

### ISSUE THREAD

**Issue by gerhardmayer-UKU** [obiba/opal#3706]
[opal.yml.txt](https://github.com/obiba/opal/files/8379875/opal.yml.txt)
Hello,

since version 4.3 of OPAL I have the problem that I cannot login anymore with the OPAL administrator password,
which I specify in the docker-compose.yml file (s. attachment).

I noted on https://www.obiba.org/pages/news/release/opal/4.3/ that there is a new password policy.
I tried dozens of passwords containing different upper case and lower case letters, as well as numbers and different special characters.
Can you describe the policy in more detail (e.g. what are the minimum and maximum length, which special characters are allowed resp. necessary, ...) ?

Until version 4.2.8 everything worked fine.
But since 4.3 the login is not working anymore.
Even going back to version 4.2 does not help.
I also tried to delete the databases and installed anew.
But I cannot login anymore with the OPAL administrator password.

Best regards,
Gerhard Mayer
University Ulm

**Comment by kazoompa** [comment]
You may want to take a look at these documentations:

https://opaldoc.obiba.org/en/latest/admin/configuration.html#cross-site-resource-forgery-csrf
https://opaldoc.obiba.org/en/latest/admin/configuration.html?highlight=apache#reverse-proxy-configuration

Also, there were a few issues related to login problems:
https://github.com/obiba/opal/issues?q=is%3Aissue+is%3Aclosed+login

Best,

**Comment by ymarcon** [comment]
There are several user "realms" in Opal and the administrator's one is called "init" realm. Users of the init realm are defined in the conf/shiro.ini file and **the password policy does not apply to this realm**. Be aware also that the docker's env variables are only applied at first run, so changing these values afterwards will have no effect. As @kazoompa has suggested, you may find in the opal.log warning messages about CSRF misconfiguration (and how to fix it).

**Comment by maharshivyas** [comment]
@ymarcon 
Thanks for your reply.
I tried after adding `csrf.allowed=*` and even the IPs to be specific to the conf/opal-config.properties file but I still get the same error message. This is just a test setup and I am accessing directly without setting up the proxy.
I also saw the issue https://github.com/obiba/opal/issues/3703 and tried accessing using the port forwarding and even then the authentication fails. 

`2022-04-05 15:47:56,102 [qtp527505741-148] INFO  org.obiba.opal.web.security.AuthenticationResource - Authentication failure of user 'administrator' at ip: 'X.X.X.X': No account information found for authentication token [org.apache.shiro.authc.UsernamePasswordToken - administrator, rememberMe=false] by this Authenticator instance.  Please check that it is configured correctly.
2022-04-05 15:50:17,306 [qtp527505741-133] WARN  org.obiba.shiro.web.filter.AbstractAuthenticationExecutor - Login failed for user 'administrator' [3]`
