### ISSUE TITLE
User & profiles from OIDC logins can see all tasks

### ISSUE THREAD

**Issue by paulusv** [obiba/opal#3720]
**Describe the bug**
In our platform we use multiple realms for agate users. We have some users with an Open ID Connect realm and some in an LDAP realm. Furthermore we use the OIDC function in Opal which creates a profile for a user logging in.

If a user who logs in via LDAP realm, OIDC realm or via the OIDC login in Opal ,is given administrative permissions to any project, the user will have access to the tasks / jobs overview tab in that project. In our deploy, it is possible to see tasks from all projects, even those the user has no permissions for at all. In our deploy, this does not happen to users in the default Agate realm, only for users logging in with alternative methods.

I've also tried to create a new user in the Opal administrative side. When creating a user like this, behaviour is as expected, no extra logs are shown.

**To Reproduce**
Setup OIDC, give user administrative rights.
Upon login with that account, you should be able to see more jobs than allowed.
Could not reproduce on opal-demo since there is no open-id connect initialized.

**Expected behavior**
Only the logs of the jobs the user has access too.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Google Chrome Versie 100.0.4896.127 (Officiële build) (64-bits)
 - Opal version 4.3.2
 - Agate version 2.53
 - Using the Coral stack

**Comment by ymarcon** [comment]
What do you mean by "give user administrative rights"? Are you referring to opal's administrative rights? If that is the case, such (super-)user will have access to everything (all projects etc.).

**Comment by paulusv** [comment]
Sorry, that was indeed unclear.
This bug occurs when we give a user administrative permissions for a single table. So when we go into a Project in Opal, select a table and from there go to permissions. We only saw this for users logged in via OIDC.

**Comment by ymarcon** [comment]
I cannot reproduce. Could it be related to your OIDC setup? Which groups are you assigning to users coming from this OIDC realm? You can verify these in the page **Administration > Profiles**.

**Comment by ymarcon** [comment]
I tried again and cannot reproduce. The **Administration / Tasks** page is empty (and there is no link to it anyway). From the project page for which OIDC user has admin rights, the tasks are visible as expected.
Whatever the realm the user signed in from, the authorizations apply the same way: permissions apply by username or by group.
Could you verify the permissions for that user, and the permissions for the SRAM group?

**Comment by paulusv** [comment]
The user only has administrative permissions to a single table. No permissions for the SRAM group are specified.
I thought this might have been the issue, but if you cannot reproduce it'll probably have to do with some of our other settings. I'll try to pinpoint the exact location and come back to you when I know more!
