### ISSUE TITLE
List permissions of a subject

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3722]
Currently permissions are visible by target (a project, a table, the datashield service etc.). It should be possible to list the permissions of a specific user or group. This would facilitate authz management. For a user, permissions listed should separate those directly granted and those inherited by the groups the user belongs to.

**Comment by kazoompa** [comment]
This has been mostly implemented in the new version Opal (in dev) with the exception of permissions separated from those directly granted and those inherited by the groups the user belongs to. In the Profile section, the a list of all persmissions can be found without how they were granted. Should this be done?
