### ISSUE TITLE
Cannot start - Opal 4.4.8 - Ubuntu 22.04

### ISSUE THREAD

**Issue by jonathanmasseurca** [obiba/opal#3743]
**Describe the bug**
I upgraded opal from 4.4.5 to 4.4.8 but after the upgade opal fail to start.

I tested 4.4.7 and the issue is there. (It cannot start)

**Expected behavior**

opal should start.

**Additional context**
Check the attached log file.
[log file.log](https://github.com/obiba/opal/files/8881720/log.file.log)

**Comment by ymarcon** [comment]
Try with 4.4.9.

**Comment by jonathanmasseurca** [comment]
It works, many thanks @ymarcon

**Comment by ymarcon** [comment]
This kind of issue happen randomly (never experienced that by the way). I have split a service in two to break thi circular dependency.
