### ISSUE TITLE
HibernateException in version 4.4

### ISSUE THREAD

**Issue by harttigu** [obiba/opal#3751]
After the recent upgrade from version 4.3.3 to the latest debian package 4.4.9, we receive an **HibernateException**  error in the webui when trying to access  or administer databases. Users also report problems accessing opal from R.

In the opal.log this shows as

<pre>2022-07-12 11:38:38,316 [qtp1474640235-6762] INFO  org.obiba.opal.core.service.DefaultDatabaseRegistry - Building SessionFactory _identifiers
2022-07-12 11:38:38,322 [qtp1474640235-6762] WARN  org.hibernate.engine.jdbc.internal.JdbcServicesImpl - HHH000342: Could not obtain connection to query metadata : Cannot create PoolableConnectionFactory (The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.)
2022-07-12 11:38:38,326 [qtp1474640235-6762] ERROR org.obiba.opal.web.provider.ErrorDtoExceptionMapper - System error Internal Server Error: com.google.common.util.concurrent.UncheckedExecutionException
com.google.common.util.concurrent.UncheckedExecutionException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '542405525-sessionFactory': Invocation of init method failed; nested exception is org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
....
2022-07-12 11:38:38,327 [qtp1474640235-6762] ERROR org.obiba.opal.web.magma.provider.UnhandledExceptionMapper - Unhandled exception HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
</pre>

Opal Version  4.4.9
Java Version 1.8.0_222
os Linux  4.19.0-8-amd64

Any pointers as how to resolve <strike>or workaround</strike> this issue are welcome.
Downgrading back to version 4.3.3 makes the opal installation operational again. However it is still unclear to me why hibernate is causing the problem with the 4.4 versions.

best regards & thank you for your help
Ulrich Harttig

**Comment by ymarcon** [comment]
I just checked and Hibernate lib version has not changed for 4 years... (by the way I am in the process of upgrading many of these core dependencies). Only Spring has been upgraded from 4.3.19 to 4.3.30.

I guess that if reverting to 4.3 fixes the issue, it is not related to your database. Which database is it? And what SQL schema are you using: Tabular SQL or Opal SQL (this one uses hibernate)?

**Comment by harttigu** [comment]
Thanks for checking on this problem. 
We use in both installations MariaDb databases for id & data with the Opal SQL. 

I further checked, guided by this warning, 
<pre>2022-07-12 11:38:38,322 [qtp1474640235-6762] WARN  org.hibernate.engine.jdbc.internal.JdbcServicesImpl - HHH000342: Could not obtain connection to query metadata : Cannot create PoolableConnectionFactory 
(The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone `support.)</pre>
and found that by explicitly setting the global timezone variable of the database, I get the correct behavior and again access to the databases.

This error occurs if after restart of the database server agian with the default timezone setting, without restart of opal
<pre>2022-07-12 17:21:16,991 [qtp11395093-107] ERROR org.obiba.opal.web.magma.provider.UnhandledExceptionMapper - Unhandled exception InvalidConnectionAttributeException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.</pre>

So it seems that the problem is somewhat specific to our local database setup, though I still wonder why the version change has triggered it.

Thanks for your help & best regards
Ulrich Harttig
