### ISSUE TITLE
Intransparent installation procedure for R packages

### ISSUE THREAD

**Issue by joerghenkebuero** [obiba/opal#3758]
**Describe the bug**
The installation of Datashield packages is not user friendly and also not working on my installation - I am completely lost.

**To Reproduce**
1. Install OPAL and ROCK on a fresh Debian Bullseye (native deb packages)
2. Configure the firewall to forbit accessing the internet, but create a proxy to get access to the CRAN packages
3. Try to install any R packages in the Administration/datashield page (Packages -> Add Package).

**Expected behavior**
If there is any reason for failing an operation in OPAL, globally, I expect an error message. Here again (like on other places), the request is executed and nothing happens. I need a success or error message about the installation of a library.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/69628891/188837312-460feabd-b6d0-4ec7-b9a0-e53fd0d1a623.png)

**Desktop (please complete the following information):**
does not matter

**Smartphone (please complete the following information):**
does not matter

**Additional context**
OPAL version: 4.4.10

**Comment by ymarcon** [comment]
dsSurvival is not in the CRAN, it is available from the "repository" Github, then you are passing the wrong parameters. And you'll need the proxy to allow connection to Github.

You should also know that the R packages installation is a always a tricky process: these are compiled, some depends on system libraries, the output is not clear and one has to dig in the R console log to find out what was wrong. This is why we recommend to build a docker image of the R server. It also ensures the reproducibility of the analysis environment. 
https://opaldoc.obiba.org/en/latest/cookbook/r-datashield/r-profiles.html#step-1-prepare-docker-images
When working in a constrained environment, other users have their own private docker registry from which they pull the R server images.

See Dockerfile for building a docker image with dsSurvival: 
https://github.com/obiba/docker-rock-demo/blob/survival/Dockerfile
