### ISSUE TITLE
Opal 4.5.0 with Google Datastore

### ISSUE THREAD

**Issue by barbaraledoux** [obiba/opal#3760]
**Describe the bug**
The project is blue with a message saying database error.

**To Reproduce**
Install Opal 4.5.0 and use Google Datastore as MongoDB.

**Expected behavior**
Working

**Additional context**
A rollback to 4.4.11 fix the issue.

**Comment by ymarcon** [comment]
Could Could you elaborate a bit? Do you mean that your accessing Google Datastore using the Mongodb driver?

**Comment by ymarcon** [comment]
Closing this issue because MongoDB driver is not supposed to be used with Google Datastore. If you would like to fund the development of a Google Datastore specific connector, let us know.

**Comment by massej** [comment]
@barbaraledoux same issue with DocumentDB on Amazon, stick with version 4.4.11 and its working well

**Comment by massej** [comment]
I didnt test Azure DocumentDB but I have the feeling that same issue will happen.
