### ISSUE TITLE
opal-server package not signed?

### ISSUE THREAD

**Issue by bjornwiberguuse** [obiba/opal#3766]
**Describe the bug**

The opal-server RPM package (from https://obiba.jfrog.io/artifactory/rpm-local) does not appear to be signed (with https://obiba.jfrog.io/artifactory/rpm-local/repodata/repomd.xml.key).

Is this perhaps something that can be fixed (enabling the signing for future releases)?
**Note:** Other OBiBa products from the same repository might be affected by this, too.

**To Reproduce**

1. Create /etc/yum.repos.d/obiba-noarch.repo with the following contents:
```[obiba-noarch]
name=obiba-noarch
baseurl=https://obiba.jfrog.io/artifactory/rpm-local
enabled=1
gpgcheck=1
gpgkey=https://obiba.jfrog.io/artifactory/rpm-local/repodata/repomd.xml.key
```
3. Install/update the opal-server package:
```
yum install opal-server
```
5. This displays the following error:
```
Package opal-server-4.5.2-1.noarch.rpm is not signed
```

**Expected behavior**

The package installs/updates without any complaints from yum.

**Comment by ymarcon** [comment]
https://access.redhat.com/articles/3359321
