### ISSUE TITLE
Deactivate access to /WEB-INF/**

### ISSUE THREAD

**Issue by fnwirth** [obiba/opal#3774]
The opal server allows access to https://myserver/WEB-INF/ (e.g. https://myserver/WEB-INF/web.xml).
Is it possible to block all HTTP requests to https://myserver/WEB-INF/** ?

Thanks a lot!

**Comment by fnwirth** [comment]
Thanks for the very fast commit.
Can you tell me when the coding changes will be incorporated in the docker container?

**Comment by ymarcon** [comment]
Opal 4.5.4 has just been released. Docker image has been updated.
