### ISSUE TITLE
401 error with administrator user

### ISSUE THREAD

**Issue by RonanMorgan** [obiba/opal#3775]
Hello,

I am using the version 4.4 of opal (and I reproduced with 4.5 also). 
I am using the following configuration :
> csrf.allowed = *

When I try to connect with the administrator passeword , I have a 401 error in my browser.

In the opal.log file, there are no errors :
`2023-01-05 10:57:20,073 [qtp513324936-30] INFO  org.obiba.opal.web.security.AuthenticationResource - Successful session creation for user 'administrator' at ip: '10.0.6.4': session ID is '053c32e6-bc81-4e98-bcc1-56bbb0ef8376'`

In the rest.log file : 
`rest.log:{"@timestamp":"2023-01-05T10:00:50.525Z","@version":"1","message":"/auth/session/_current/username","logger_name":"org.obiba.opal.web.security.AuditInterceptor","thread_name":"qtp332564935-43","level":"WARN","level_value":30000,"method":"GET","ip":"10.0.4.4","username":"Unknown","status":"401"}`

Do you have any idea why ?

**Comment by ymarcon** [comment]
It does not look like a CSRF issue otherwise there would be a specific log message.

Do you access opal through `http` or `https`?

**Comment by RonanMorgan** [comment]
I am using `http` since we are working in a private network (and we don't have a PKI for now)

**Comment by ymarcon** [comment]
Since [Opal 4.3](https://www.obiba.org/pages/news/release/opal/4.3/) the cookies are only accessible through `https` (`Secure` flag). In your private network, there is no problem at using the default `https` key pair: just accept that it is a self-signed one in your browser. The Python and R clients can handle that as well.

**Comment by RonanMorgan** [comment]
ok thanks I am gonna try that !
