### ISSUE TITLE
More information for system admins when DataSHIELD packages are being installed

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3780]
**Background**

When system administrators install DataSHIELD packages, there is not much information about the progress of the installation, or whether the installation succeeds or fails. This can be confusing for the administrator, particularly when it takes a long time to install

**Desired behaviour**
Some kind of progress indicator or at least message that explains that installation is ongoing rather than the "spinning mouse pointer"
A message saying that the installation is complete (preferably success or failure)

**Additional context**
I can see that this might be challenging because the installation is going on in R not Opal. Is it possible to retrieve some of the messages that end up in RServe.log to display on screen to show that something is happening?

**Comment by ymarcon** [comment]
The R base `install.packages()` is very limited in terms of interaction. Possible solution is to wrap it in another function:

https://stackoverflow.com/a/72453981/4875643

**Comment by tombisho** [comment]
Hi Yannick, yes I can understand that this is all happening in R so it might be difficult. At the very least it might be good to have a message reassuring users that "installation is in progress and that it can take some time" would help.

It is not the most urgent thing but I wanted to record the feedback I got from users

**Comment by ymarcon** [comment]
You can also tell them that the best practice is to have a reproducible R environment and installing R packages like that is not the way to go. Docker images is the solution. (I know you know that)

**Comment by tombisho** [comment]
Yes that is a good point.... I am slowly getting people moved over. However, some prefer Coral, and for this I think you still need to be able to install packages. I don't think at the moment Coral can cope with having another Rock server with a different config running in Docker as well?
