### ISSUE TITLE
Problems with environment variable APP_URL

### ISSUE THREAD

**Issue by djuarezgf** [obiba/opal#3796]
**Describe the bug**
Our Opal instance runs in a docker container behind a reverse proxy (Traefik). In order to access the container of Opal, we have configured in Traefik the prefix "/opal". The URL will be as following: https://XXXX/opal. In the docker-compose file, we have set this value in the variable APP_URL (APP_URL: "https://XXXX/opal").

The traefik configuration looks at follows:
      - "traefik.enable=true"
      - "traefik.http.routers.opal_ccp.rule=PathPrefix(`/opal`)"
      - "traefik.http.services.opal_ccp.loadbalancer.server.port=8080"
      - "traefik.http.routers.opal_ccp.tls=true"
      - "traefik.http.middlewares.opal_ccp_strip.stripprefix.prefixes=/opal"
      - "traefik.http.routers.opal_ccp.middlewares=opal_ccp_strip"

When we call https://XXXX/opal, the browser does the following:
GET https://XXXX/opal
GET https://XXXX/opal/index.html
GET https://XXXX/opal/ui/index.html
...
GET https://XXXX/ws/auth/session/_current/username

As we see, "/ui" is correctly inserted after the prefix "/opal", however, it doesn't happen the same with "/ws". When Opal calls WS, the prefix "/opal" disappears. 

Are we missing any configuration or is there any error with APP_URL?

**Comment by ymarcon** [comment]
You need to declare the server context path in opal-config.properties:

```
org.obiba.opal.server.context-path=/opal
```

**Comment by djuarezgf** [comment]
Would it be possible to add an environment variable for the docker image to set that value? For example, APP_CONTEXT_PATH. It would be set in https://github.com/obiba/docker-opal/blob/master/bin/start.sh . Something like this:

`  if [ -n "$APP_CONTEXT_PATH" ]
  then
    set_property "org.obiba.opal.server.context-path" "$APP_CONTEXT_PATH" "$OPAL_HOME/conf/opal-config.properties"
  fi
`

**Comment by ymarcon** [comment]
Sounds like a reasonable request.

**Comment by ymarcon** [comment]
Opal docker images `4.5` and `latest` updated. Please give it a try.

**Comment by djuarezgf** [comment]
Thank you very much for the new variable. I have tried it: When I call internally in the container “cat /config/opal-config.properties”, I get the following properties:
org.obiba.opal.public.url=https://XXX/opal
org.obiba.opal.server.context-path = /opal

Unfortunately, when I call in the browser https://xxx/opal, at some point, Opal tries to reach the following URL:
https://xxx/ws/auth/session/_current/username
I realized that there was another parameter:
org.obiba.shiro.authenticationFilter.requestPrefix=/ws/
I tried to change it manually to 
org.obiba.shiro.authenticationFilter.requestPrefix=/opal/ws/

However, this change didn’t have any effect. Somehow, Opal ignores APP_URL and APP_CONTEXT_PATH for the authentication in /ws

**Comment by ymarcon** [comment]
the context-path is enough. Maybe there is a mix up with docker and the reverse proxy? FYI this setting has been operational for years, and some people use it with docker.

**Comment by djuarezgf** [comment]
I have tried the APP_CONTEXT_PATH without the traefik environment and I still have problems:

  opal:
    image: obiba/opal:4.5
    ports:
      - "8843:8443" # HTTPS
      - "8880:8080" # HTTP
    links:
      - opal-rserver
      - opal-mongo
      - opal-db
    environment:
...
      APP_URL: "http://localhost:8880/opal"
      APP_CONTEXT_PATH: "/opal"


I call in the browser http://localhost:8880/opal and it happens the following:
GET http://localhost:8880/opal
GET http://localhost:8880/opal/
GET http://localhost:8880/opal/index.html
GET http://localhost:8880/index.html
GET http://localhost:8880/ui/index.html
...
GET http://localhost:8880/ws/auth/session/_current/username

Are we missing any parameters in the configuration of the UI?

**Comment by ymarcon** [comment]
Looks like a regression. Let me check.

**Comment by ymarcon** [comment]
Fix available in opal 4.5.8, obiba/opal image updated accordingly.

**Comment by ymarcon** [comment]
Good catch, please pull image and try again.

**Comment by djuarezgf** [comment]
It works!

**Comment by ymarcon** [comment]
Excellent, thanks for your help!
