### ISSUE TITLE
Opal admin reports that "packages are inconsistent between the R servers" - probably false positive

### ISSUE THREAD

**Issue by fnwirth** [obiba/opal#3806]
**Describe the bug**
I added a second rock-server after deleting the volume and the container of the first one. Therefore, both rock servers should be "brand new" and on the same version level. However, on the DataSHIELD-admin page a message is displayed that "packages are inconsistent between the R servers" (please see screenshot). The version numbers are equal.
The problem remains when I use the "Delete all" button and re-install the ds-base packages using the "Add package" button. Is this a false-positive warning message?

**To Reproduce**
1. Use opal imageswith one rock image
2. Add a second rock image
3. Go to "DataSHIELD" under Administration

**Expected behavior**
Not see a warning message

**Screenshots**
![grafik](https://github.com/obiba/opal/assets/62593896/aa318db5-7d11-45a4-8e33-f6a3e007b938)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox and Edge

**Additional context**
Installation based on the docker compose file here: https://opaldoc.obiba.org/en/latest/admin/installation.html

**Comment by ymarcon** [comment]
This happens when the R servers have the same name. In the Rock configuration, the name is provided by the `node.id` properties.

**Comment by ymarcon** [comment]
Improvement implemented: registered R server has a unique name, even if the rock servers use the same id (82d3a2dc393b3f2a69b5d49c43d6e09a54457dce and 11b1600296e2107f7cf3d1a5601d27a0e1d19536)

![image](https://github.com/obiba/opal/assets/2581149/65c427e1-3938-4688-8460-470c76794974)
