### ISSUE TITLE
AUR Version

### ISSUE THREAD

**Issue by ParadaCarleton** [obiba/opal#3808]
**Is your feature request related to a problem? Please describe.**
It's difficult to install Opal on Arch linux.

**Describe the solution you'd like**
Add Opal to the Arch User Repository (AUR).

**Comment by kazoompa** [comment]
yay -S debtap
debtap yourfile.deb

**Comment by ymarcon** [comment]
What about using docker? Docker is the recommended packaging for the R server part btw.
