### ISSUE TITLE
Unable to Access Opal in RStudio with Keycloak Credentials for Users Registered in Keycloak but Not in Opal

### ISSUE THREAD

**Issue by arturofigueroabim** [obiba/opal#3809]
I am facing an issue with accessing Opal in RStudio using Keycloak credentials for users who are registered in Keycloak but not in Opal. Here's a detailed description of the problem:

Scenario:

We have implemented Keycloak as the Single Sign-On (SSO) solution for our system.
Users are registered in Keycloak, but they are not registered in Opal.
Expected Behavior:

We expect that users who are registered in Keycloak can use their Keycloak credentials to access Opal in RStudio through DataShield.
Actual Behavior:

When attempting to access Opal in RStudio using the Keycloak credentials of a user registered in Keycloak but not in Opal, we encounter authentication errors or issues.
Steps to Reproduce:

Log in to RStudio with Keycloak credentials.
Attempt to access Opal in RStudio using the Keycloak credentials.
Error Messages:

We have received various error messages, such as "Unauthorized (401)" or other related authentication errors.
Code Snippet:
`library(DSI)
library(DSOpal)
library(dsBaseClient)

# Replace the placeholders with the actual Keycloak access token
keycloak_token <- "Bearer YOUR_KEYCLOAK_ACCESS_TOKEN_HERE"

# Create a new DSLoginBuilder
builder <- DSI::newDSLoginBuilder(.silent = FALSE)

# Append Opal server information and the Keycloak access token to the builder
builder$append(
  server = 'YOUR_OPAL_SERVER_NAME',               # Replace with your Opal server name
  url = "YOUR_OPAL_SERVER_URL",                   # Replace with your Opal server URL
  token = keycloak_token,
  driver = "OpalDriver",
  options = "list(ssl_verifyhost=0,ssl_verifypeer=0)"   # Replace with other options as needed
)

# Build the login data
logindata <- builder$build()

# Perform DataShield login using the login data
connections <- DSI::datashield.login(logins = logindata, assign = TRUE, symbol = "D")

# You can now perform DataShield operations with the connections
# For example, you can assign a table to a symbol
DSI::datashield.assign.table(conns = connections, symbol = "DST", table = c("YOUR_TABLE_NAME"))
`

Additional Information:

We have successfully generated the Keycloak access token using the provided code in RStudio.
Users are correctly registered in Keycloak with appropriate roles and permissions.
However, when attempting to use the access token to access Opal through DataShield in RStudio, we encounter the "Unauthorized (401)" error.
Note:

We are not sure if there is an additional configuration required either in Keycloak or Opal to enable this functionality.
Any assistance or guidance on resolving this issue would be greatly appreciated. Please let us know if more information is needed. Thank you for your help!

**Comment by ymarcon** [comment]
1. Set Keycloak as an Opal's ID provider so that KC users are known by Opal: https://opaldoc.obiba.org/en/latest/web-user-guide/administration/identity-providers.html
2. When doing scripting work, it is much more secure to use in Datashield a Personal access token: https://opaldoc.obiba.org/en/latest/web-user-guide/my-profile.html#personal-access-tokens

**Comment by arturofigueroabim** [comment]
> 

Thank you for your response. However, I believe there might have been a misunderstanding with my initial issue. Keycloak has already been set as the identity provider in our Opal configuration, so your suggestion is in line with our existing setup.

The core of the issue is that we are trying to facilitate users, who are registered in Keycloak but not in Opal, to access Opal via RStudio. Despite their Keycloak registration and proper authentication, we've encountered problems when these specific users attempt to leverage their Keycloak credentials in RStudio.

Regarding the use of DataShield's Personal access token, we acknowledge its increased security during scripting work. However, this solution presupposes that a user has successfully signed in to Opal, which is the step that our users are unable to reach in the first place due to the aforementioned authentication issue.

Our objective is to streamline the workflow, ideally bypassing the need for manual registration in Opal if the user is already registered in Keycloak.

We'd appreciate any additional insights or alternative solutions you might suggest to help us resolve this issue.

Thank you for your time and assistance.

**Comment by ymarcon** [comment]
If Kc is an ID provider of Opal, why users would not be able to login in Opal to make their PAT? Is the Kc setup misconfigured?

**Comment by arturofigueroabim** [comment]
Keycloak is not misconfigured, I think it is better to explain with some screenshots.

**1. Keycloak Configuration in Opal:**
After correctly configuring and enabling Keycloak (KC) in Opal, there's a button that allows users the option to log in through Keycloak.
![image](https://github.com/obiba/opal/assets/23725543/200192cb-fbc8-4d38-956f-47710b00c0c4)

**2. Sign-in Process with Keycloak:**
In this step, I'm demonstrating using credentials of a user already registered in Keycloak to sign in.
![image](https://github.com/obiba/opal/assets/23725543/ff5170e9-02b9-457b-aee1-382a545ec484)

**3. Successful Access and User Registration in Opal:**
Upon entering valid Keycloak credentials, access to Opal is granted. The authenticated user is then registered under the "Administration/Profiles" section, effectively becoming a local user in Opal.
![image](https://github.com/obiba/opal/assets/23725543/5cd00afd-ae95-49b3-be9e-b42eefede487)

**4. Issue Authentication in RStudio through DataShield:**
The problem arises when I try to use the previous user or any new user who is registered in Keycloak, I'm unable to authenticate them through DataShield in RStudio. I am getting the following Unauthorized error.
![image](https://github.com/obiba/opal/assets/23725543/0ebc31f7-256a-457a-9441-904c243de877)


I hope this clarify a little more my situation. We'd appreciate any additional insights you might suggest to help us resolve or clarify our issue.

Thank you for your time and assistance.

**Comment by arturofigueroabim** [comment]
Got it! Thanks for breaking it down for me. Sounds like the PAT with datashield scope is the way to go. Really appreciate the quick reply.

Thak you for your help and your time!
