### ISSUE TITLE
Opal will not start with Java-11/17

### ISSUE THREAD

**Issue by tuxmaster5000** [obiba/opal#3810]
### This issue is unique

- [X] I have used the [search tool](https://github.com/obiba/Opal/issues?q=) and did not find an issue describing my bug.

### Version information

4.6.3-1

### Expected behavior

Working with OpenJDK11

### Actual behavior

Error message on start:

> 2023-08-29 09:04:45,790 [main] WARN  org.springframework.context.support.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jotm' defined in class path resource [spring/opal-core/tx.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.obiba.opal.core.tx.JotmFactoryBean]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
> 2023-08-29 09:04:45,794 [main] ERROR org.obiba.opal.server.OpalServer - Exception
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jotm' defined in class path resource [spring/opal-core/tx.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.obiba.opal.core.tx.JotmFactoryBean]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:936)
>         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
>         at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
>         at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
>         at org.obiba.opal.server.UpgradeCommand.standardUpgrade(UpgradeCommand.java:53)
>         at org.obiba.opal.server.UpgradeCommand.execute(UpgradeCommand.java:49)
>         at org.obiba.opal.server.OpalServer.upgrade(OpalServer.java:104)
>         at org.obiba.opal.server.OpalServer.<init>(OpalServer.java:39)
>         at org.obiba.opal.server.OpalServer.main(OpalServer.java:154)
> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.obiba.opal.core.tx.JotmFactoryBean]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
>         at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
>         at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
>         ... 17 common frames omitted
> Caused by: java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
>         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
>         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)
>         at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
>         at org.objectweb.jotm.Jotm.<init>(Jotm.java:143)
>         at org.obiba.opal.core.tx.JotmFactoryBean.<init>(JotmFactoryBean.java:85)

### Reproduction steps

Start the service:

> systemctl start opal

OS: Rocky 9

### Operating System (OS)

Linux

### Browser

FireFox

**Comment by ymarcon** [comment]
Java 11 is not supported, as stated in the documentation, mainly because of the GWT library used for building the frontend.

**Comment by tuxmaster5000** [comment]
I have also tested it with Java 17, the same.

**Comment by tuxmaster5000** [comment]
Since 2022 Java 9+ will be supported by GWT:
https://www.gwtproject.org/release-notes.html

**Comment by ymarcon** [comment]
I know but it is not that simple to upgrade GWT *and* the additional libraries.

**Comment by tuxmaster5000** [comment]
Ok I understand. Do you have an time table for it? 
When I  look to OpenJDK live cycle map, then OpenJDK 17 support make more sense, because OpenJDK 11 will be eol before 8. And 17  will be after 8.

**Comment by tuxmaster5000** [comment]
What will be the current state?

**Comment by ymarcon** [comment]
Fixed in Opal 5, to be released in the coming week.
