### ISSUE TITLE
ERROR: LogManager is shutdown, no logging is possible !!!

### ISSUE THREAD

**Issue by djuarezgf** [obiba/opal#3811]
### This issue is unique

- [X] I have used the [search tool](https://github.com/obiba/Opal/issues?q=) and did not find an issue describing my bug.

### Version information

4.6

### Actual behavior

Since I have updated Opal to 4.6, I get the following message:
ERROR: LogManager is shutdown, no logging is possible !!!

Am I missing something in the configuration?

### Operating System (OS)

Linux

### Contact info

Deutsches Krebsforschungszentrum (Federated Information Systems)
https://www.dkfz.de/en/index.html

**Comment by ymarcon** [comment]
Fixed in Opal 5, to be released in the coming week.
