### ISSUE TITLE
[4.6.4] Many  "Duplicate key" errors on start up and when importing data to an project

### ISSUE THREAD

**Issue by tuxmaster5000** [obiba/opal#3812]
### This issue is unique

- [X] I have used the [search tool](https://github.com/obiba/Opal/issues?q=) and did not find an issue describing my bug.

### Version information

4.6.4

### Expected behavior

That the scientists  can import data to projects.

### Actual behavior

He/she will only see an error about an "duplicate key error"

### Reproduction steps

1. log in
2. go to project -> tables
3.  use import

### Operating System (OS)

Linux

**Comment by ymarcon** [comment]
I would not recommend to use the Hibernate type of database: it has strong limitations, poor performance, and as it is difficult to maintain, it will not be supported any more in a near future. Mongodb is the recommended storage backend. If you want to keep on with SQL, prefer the "Tabular SQL" schema.

**Comment by tuxmaster5000** [comment]
Hi, we use the "Tabulator Schema" as far as possible. How can we convert the rest?
Mongodb will not be an option, because it will not have an incremental backup/restore function on none cloud setup's.
Here the data sources:
![Screenshot 2023-10-17 at 07-53-19 MDC Opal](https://github.com/obiba/opal/assets/837503/3e854f30-4d2e-4db3-a200-812afdcbed04)

**Comment by tuxmaster5000** [comment]
"Tabular SQL" schema, will also fails:
1. create an storage database with schema "Tabular SQL"
2.  create an new project using this storage.
Error:

> 2023-10-17 12:36:37,809 [qtp217062446-1812] INFO  org.obiba.opal.core.service.ProjectsState - Project foo to state LOADING                                                                                         
> 2023-10-17 12:36:37,809 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DatasourceLoaderServiceImpl - Datasource Loader 2: loading datasource of project foo                                               
> 2023-10-17 12:36:37,809 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DatasourceLoaderServiceImpl -   Datasource load start: foo                                                                         
> 2023-10-17 12:36:37,812 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DefaultDatabaseRegistry - Building DataSource Data2                                                                                
> 2023-10-17 12:36:37,816 [qtp217062446-1812] INFO  org.obiba.opal.core.service.security.realm.SpatialRealm - Clear cache perms for USER:administrator                                                               
> 2023-10-17 12:36:37,853 [Datasource Loader 2] WARN  org.mariadb.jdbc.message.server.ErrorPacket - Error: 1071-42000: Specified key was too long; max key length is 3072 bytes                                      
> 2023-10-17 12:36:37,854 [Datasource Loader 2] ERROR org.obiba.opal.core.service.DatasourceLoaderServiceImpl - Datasource Loader 2: loading datasource of project foo failed for database: Data2                    
> org.obiba.magma.MagmaRuntimeException: org.springframework.jdbc.UncategorizedSQLException: ConnectionCallback; uncategorized SQLException; SQL state [null]; error code [0]; liquibase.exception.DatabaseException:
>  (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VAR
> CHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]; nested exception is java.sql.SQLException:
>  liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table
> ` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]     
>         at org.obiba.magma.support.Initialisables.initialise(Initialisables.java:50)                                                                                                                               
>         at org.obiba.magma.DefaultDatasourceRegistry.addDatasource(DefaultDatasourceRegistry.java:99)                                                                                                              
>         at org.obiba.magma.DefaultDatasourceRegistry.addDatasource(DefaultDatasourceRegistry.java:123)                                                                                                             
>         at org.obiba.magma.security.SecuredDatasourceRegistry.addDatasource(SecuredDatasourceRegistry.java:49)                                                                                                     
>         at org.obiba.magma.MagmaEngine.addDatasource(MagmaEngine.java:146)                                                                                                                                         
>         at org.obiba.opal.core.service.DatasourceLoaderServiceImpl.lambda$reloadDatasource$1(DatasourceLoaderServiceImpl.java:107)                                                                                 
>         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)                                                                                                       
>         at org.obiba.opal.core.service.DatasourceLoaderServiceImpl.reloadDatasource(DatasourceLoaderServiceImpl.java:92)
>         at org.obiba.opal.core.service.DatasourceLoaderServiceImpl$DatasourceLoader.load(DatasourceLoaderServiceImpl.java:137)
>         at org.obiba.opal.core.service.DatasourceLoaderServiceImpl$DatasourceLoader.run(DatasourceLoaderServiceImpl.java:126)
> Caused by: org.springframework.jdbc.UncategorizedSQLException: ConnectionCallback; uncategorized SQLException; SQL state [null]; error code [0]; liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]; nested exception is java.sql.SQLException: liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]
>         at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1578)
>         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:344)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource.doWithDatabase(JdbcDatasource.java:508)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource.createMetadataTablesIfNotPresent(JdbcDatasource.java:552)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource.onInitialise(JdbcDatasource.java:237)
>         at org.obiba.magma.support.AbstractDatasource.initialise(AbstractDatasource.java:101)
>         at org.obiba.magma.support.AbstractDatasourceWrapper.initialise(AbstractDatasourceWrapper.java:52)
>         at org.obiba.magma.views.ViewAwareDatasource.initialise(ViewAwareDatasource.java:47)
>         at org.obiba.magma.support.Initialisables.initialise(Initialisables.java:46)
>         ... 9 common frames omitted
> Caused by: java.sql.SQLException: liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource$3.doInConnection(JdbcDatasource.java:519)
>         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:336)
>         ... 16 common frames omitted
> Caused by: liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource$3.doInConnection(JdbcDatasource.java:519)
>         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:336)
>         ... 16 common frames omitted
> Caused by: liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]
>         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:440)
>         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:78)
>         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:161)
>         at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1299)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource$ChangeDatabaseCallback.doInDatabase(JdbcDatasource.java:685)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource$3.doInConnection(JdbcDatasource.java:517)
>         ... 17 common frames omitted
> Caused by: java.sql.SQLSyntaxErrorException: (conn=671) Specified key was too long; max key length is 3072 bytes
>         at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:280)
>         at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
>         at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
>         at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:833)
>         at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:772)
>         at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:691)
>         at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:634)
>         at org.mariadb.jdbc.Statement.executeInternal(Statement.java:935)
>         at org.mariadb.jdbc.Statement.execute(Statement.java:1061)
>         at org.mariadb.jdbc.Statement.execute(Statement.java:452)
>         at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:193)
>         at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:193)
>         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:436)
>         ... 22 common frames omitted
> 2023-10-17 12:36:37,855 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DefaultDatabaseRegistry - Destroying DataSource Data2
> 2023-10-17 12:36:37,855 [Datasource Loader 2] INFO  org.obiba.opal.core.service.ProjectsState - Project foo to state ERRORS
> 
In the UI:
Errors: the database could not be loaded because of errors.

**Comment by ymarcon** [comment]
What is the version of MariaDB? Do you have specific settings for this database?

**Comment by tuxmaster5000** [comment]
We use MariaDB 10.11.5, the LTS version.
But I can upload the variable list, because GH rejects the file. :(

**Comment by tuxmaster5000** [comment]
To day I have tested "Tabular SQL" with PostgreSQL (version 12) which are selectable in the ui.
Here the  "Tabular SQL"  schema will works. Looking deeper in the limit specification of both data base systems the problem is very clear. PostgreSQL has only an column limit of 32 for indexes. MariaDB will have an hard coded byte limit for it, which depend on the InnoDB page size. Using an page size of 16KB which is the default will limit the index to  3072 bytes. Increase the page size are possible, but dangerous because you will lost table types, which are not an option, when  other application also use the data base server. So in my eyes only the move to PostgreSQL or reduce the fields in the index can fix it.

**Comment by ymarcon** [comment]
I have tested both mysql and mariadb, the tabular SQL works up to the following versions:

* mysql 8.0.0 (8.0.1 is NOT working)
* mariadb: 10.4 (10.5 is NOT working)

It is very annoying that database vendors introduce breaking changes on non major versions. I will work on a fix.

**Comment by ymarcon** [comment]
Fix tested with mysql 8.1 and mariadb 11 (latests)

**Comment by tuxmaster5000** [comment]
@ymarcon thanks.
But what will be the feature of postgresql?

**Comment by tuxmaster5000** [comment]
Thanks.
