### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by massej** [obiba/opal#3816]
Is there a settings to disable the default login page and redirect to the OAuth 2 page?

I was not able to find any information in the manual to disable the login page

<img width="1183" alt="image" src="https://github.com/obiba/opal/assets/22155257/bd9f1940-e746-4555-8a8b-7f7de837793f">

Thank you for your help,

**Comment by kazoompa** [comment]
Hi,

You cannot remove the login page and Opal does not yet support client-code (UI) customisation.

Best,

**Comment by massej** [comment]
Thank you for the quick reply,

Best,
