### ISSUE TITLE
feat(ui): system admin

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3835]
- [x] general settings
- [x] taxonomies
- [x] databases
- [x] plugins
- [x] apps

**Comment by kazoompa** [comment]
You mentioned some new changes wth respect to loading plugins in new Java, could you list them here.

**Comment by kazoompa** [comment]
By the way, this is a nice lib to prevent more dev:

[dif2html](https://diff2html.xyz/), does the diffing. Here is a quick test in Opal:


![image](https://github.com/user-attachments/assets/f3d8316d-a871-47a8-b275-a07606bf1155)

We can have it in a popup and add other info like the old one on top

**Comment by ymarcon** [comment]
When the list of terms is filtered, the action buttons (edit, delete, moves) are not visible:

![image](https://github.com/user-attachments/assets/2161efb8-130e-4ee5-9adc-75167c169598)

**Comment by kazoompa** [comment]
I reproduced the old functionality, I'll check it out ...

**Comment by kazoompa** [comment]
I have a PR only for editing and deleting terms in a table, moving is a little confusing since the orders are based on the actual data and not the filtered one. You could move up and see no changes because the item before is in fact several indices above. Anyways, we can leave without for now.
