### ISSUE TITLE
Question:  column "code" in categories dictionary

### ISSUE THREAD

**Issue by TMJansen** [obiba/opal#3862]
In a dictionary download from Opal, sheet Categories, there is an empty column "code".
Can you please let me know what this column is intended for, and if used, what information I could find there?
(As the actual code is in the column "name", this is unclear to us).
Thank you very much for your answer.

**Comment by ymarcon** [comment]
The actual code is the name, this column is a legacy, you can ignore/remove it.

**Comment by TMJansen** [comment]
Thank you!
