### ISSUE TITLE
MR-QA - Summary range does not have any effect

### ISSUE THREAD

**Issue by kazoompa** [obiba/opal#3950]
### This issue is unique

- [X] I have used the [search tool](https://github.com/obiba/Opal/issues?q=) and did not find an issue describing my bug.

### Version information

4.7.x, 5.0.0

### Expected behavior

If the range is set to 10-200, the results must correspnds to that input.

### Actual behavior

The result is the same as before and the range resets.

### Reproduction steps

- Go to a table with continuous variables
- Go to the Suammry section and make sure the index is refreshed
- Change the range from for example: 200-200 to 10-200

**Comment by ymarcon** [comment]
There is no such thing as "summary range". There is only a limit and it does not apply when summary is cached.

**Comment by kazoompa** [comment]
Range might have been the wrong term but it confused many users as no matter what they do the result is the same rendering the summary useless.

My suggestion is to have `fullIfCached` to be the default when landing in this section. If user changes the limit, this should not be set to true to prevent the error above. 

It would be equally nice to let the user get a fresh summary and have `resetCache` set to true.

The only way to get different result was to call as follows:
```
>opal rest "/datasource/FNAC/table/FNAC/variable/SVUOSI/summary?fullIfCached=false&limit=300&resetCache=true"  -o http://localhost:8080 -u administrator -p password    -a application/json -j > /tmp/FNAC_SVUOSI_summary.json
```
