### ISSUE TITLE
MR-QA - Missing UI to render repeating variable values

### ISSUE THREAD

**Issue by kazoompa** [obiba/opal#3963]
### This issue is unique

- [X] I have used the [search tool](https://github.com/obiba/Opal/issues?q=) and did not find an issue describing my bug.

### Version information

5.0.0

### Expected behavior

Like the older versions, represent the values via a list or a popup. 

### Actual behavior

If a participant has N values for a given variables, there are N rows in the table cell which is not practical.  

### Reproduction steps

- Go to Search / Entity search
- Look for ID 100
- Select table `GSS-tu.1986_1`

**Comment by ymarcon** [comment]
Cannot reproduce: the repeatable values are already displayed as a list.

**Comment by kazoompa** [comment]
The staging is updated with snapshot and I still see the values not like before, i.e., a button user could click and see the repeated values:

https://opal-staging.maelstrom-research.org/index.html#/project/GSS-tu/table/1986_1/variable/DDAY

**Comment by ymarcon** [comment]
It is different but it is there.
